/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.technoComplex.views;

import com.technoComplex.model.FlatModel;
import com.technoComplex.model.TenantModel;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prajwal Luitel LMU Id 23048626
 */
public class Dashboard extends javax.swing.JFrame {

    private List<TenantModel> tenantList;
    private List<FlatModel> flatList;

    /**
     * Creates new form Dashboard populate both tables with the data
     */
    public Dashboard() {
        initComponents();
        initializeData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDashboardMain = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        lblMenuTitleIcon = new javax.swing.JLabel();
        lblMenuTitle = new javax.swing.JLabel();
        lblMenuTitleBoder = new javax.swing.JLabel();
        pnlMenuHome = new javax.swing.JPanel();
        lblMenuHomeIcon = new javax.swing.JLabel();
        lblMenuHomeTitle = new javax.swing.JLabel();
        pnlMenuDashboard = new javax.swing.JPanel();
        lblMenuDashboardIcon = new javax.swing.JLabel();
        lblMenuDashboardTitle = new javax.swing.JLabel();
        lblMenuManageLeftBoder = new javax.swing.JLabel();
        lblMenuManageTitle = new javax.swing.JLabel();
        lblMenuManageRightBoder = new javax.swing.JLabel();
        pnlMenuManageFlat = new javax.swing.JPanel();
        lblMenuManageFlatIcon = new javax.swing.JLabel();
        lblMenuManageFlatTitle = new javax.swing.JLabel();
        pnlMenuManageTenant = new javax.swing.JPanel();
        lblMenuManageTenantIcon = new javax.swing.JLabel();
        lblMenuManageTenantTitle = new javax.swing.JLabel();
        lblMenuSortAndSearchLeftBoder = new javax.swing.JLabel();
        lblMenuSortAndSearchTitle = new javax.swing.JLabel();
        lblMenuSortAndSearchRightBoder = new javax.swing.JLabel();
        pnlMenuSortAndSearchFlat = new javax.swing.JPanel();
        lblMenuSortAndSearchFlatIcon = new javax.swing.JLabel();
        lblMenuSortAndSearchFlatTitle = new javax.swing.JLabel();
        pnlMenuSortAndSearchTenant = new javax.swing.JPanel();
        lblMenuSortAndSearchTenantIcon = new javax.swing.JLabel();
        lblMenuSortAndSearchTenantTitle = new javax.swing.JLabel();
        lblMenuSettingLeftBoder = new javax.swing.JLabel();
        lblMenuSettingTitle = new javax.swing.JLabel();
        lblMenuSettingRightBoder = new javax.swing.JLabel();
        pnlMenuSettingLogout = new javax.swing.JPanel();
        lblMenuSettingLogoutIcon = new javax.swing.JLabel();
        lblMenuSettingLogoutTitle = new javax.swing.JLabel();
        lblMenuBackgroundImage = new javax.swing.JLabel();
        lblLoginClose = new javax.swing.JLabel();
        lblViewTenantDetails = new javax.swing.JLabel();
        scrlpnMangeTenantTable = new javax.swing.JScrollPane();
        tblMangeTenant = new javax.swing.JTable();
        lblViewFlatDetails = new javax.swing.JLabel();
        scrlpnMangeFlatTable = new javax.swing.JScrollPane();
        tblMangeFlat = new javax.swing.JTable();
        lblCountOfRentedFlat = new javax.swing.JLabel();
        lblRentedFlatBackground = new javax.swing.JLabel();
        lblAvailable = new javax.swing.JLabel();
        lblForRent = new javax.swing.JLabel();
        lblCountOfAvailableRent = new javax.swing.JLabel();
        lblAvailableForRentBackground = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblIncome = new javax.swing.JLabel();
        lblCountOfTotalIncome = new javax.swing.JLabel();
        lblTotalIncomeBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1706, 912));
        setMinimumSize(new java.awt.Dimension(1706, 912));
        setName("Dashboard"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1706, 912));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDashboardMain.setBackground(new java.awt.Color(232, 245, 255));
        pnlDashboardMain.setMaximumSize(new java.awt.Dimension(1706, 912));
        pnlDashboardMain.setMinimumSize(new java.awt.Dimension(1706, 912));
        pnlDashboardMain.setPreferredSize(new java.awt.Dimension(1706, 912));
        pnlDashboardMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenu.setMaximumSize(new java.awt.Dimension(371, 912));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuTitleIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technoComplex/resources/image/icons/whiteTechnoLogo.png"))); // NOI18N
        pnlMenu.add(lblMenuTitleIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 10, 220, 150));

        lblMenuTitle.setFont(new java.awt.Font("Poppins", 2, 26)); // NOI18N
        lblMenuTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuTitle.setText("Techno Complex");
        pnlMenu.add(lblMenuTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 230, 80));

        lblMenuTitleBoder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        pnlMenu.add(lblMenuTitleBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 370, 60));

        pnlMenuHome.setMaximumSize(new java.awt.Dimension(371, 60));
        pnlMenuHome.setMinimumSize(new java.awt.Dimension(371, 60));
        pnlMenuHome.setOpaque(false);
        pnlMenuHome.setPreferredSize(new java.awt.Dimension(371, 60));
        pnlMenuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenuHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMenuHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMenuHomeMouseExited(evt);
            }
        });
        pnlMenuHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuHomeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technoComplex/resources/image/icons/home_16dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        lblMenuHomeIcon.setText("jLabel11");
        pnlMenuHome.add(lblMenuHomeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 70, 50));

        lblMenuHomeTitle.setFont(new java.awt.Font("Poppins", 0, 28)); // NOI18N
        lblMenuHomeTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuHomeTitle.setText("Home");
        pnlMenuHome.add(lblMenuHomeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        pnlMenu.add(pnlMenuHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        pnlMenuDashboard.setBackground(new java.awt.Color(97,97,97,120));
        pnlMenuDashboard.setMaximumSize(new java.awt.Dimension(371, 60));
        pnlMenuDashboard.setMinimumSize(new java.awt.Dimension(371, 60));
        pnlMenuDashboard.setPreferredSize(new java.awt.Dimension(371, 60));
        pnlMenuDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuDashboardIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technoComplex/resources/image/icons/dashboard_16dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        pnlMenuDashboard.add(lblMenuDashboardIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 6, -1, 48));

        lblMenuDashboardTitle.setFont(new java.awt.Font("Poppins", 0, 28)); // NOI18N
        lblMenuDashboardTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuDashboardTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuDashboardTitle.setText("Dashboard");
        pnlMenuDashboard.add(lblMenuDashboardTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 6, -1, -1));

        pnlMenu.add(pnlMenuDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        lblMenuManageLeftBoder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        pnlMenu.add(lblMenuManageLeftBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 130, 10));

        lblMenuManageTitle.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblMenuManageTitle.setForeground(new java.awt.Color(191, 191, 191));
        lblMenuManageTitle.setText("Manage");
        pnlMenu.add(lblMenuManageTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 90, 20));

        lblMenuManageRightBoder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        pnlMenu.add(lblMenuManageRightBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 150, 10));

        pnlMenuManageFlat.setMaximumSize(new java.awt.Dimension(371, 60));
        pnlMenuManageFlat.setMinimumSize(new java.awt.Dimension(371, 60));
        pnlMenuManageFlat.setOpaque(false);
        pnlMenuManageFlat.setPreferredSize(new java.awt.Dimension(371, 60));
        pnlMenuManageFlat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenuManageFlatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMenuManageFlatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMenuManageFlatMouseExited(evt);
            }
        });
        pnlMenuManageFlat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuManageFlatIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technoComplex/resources/image/icons/room_preferences_16dp_FFFFFF_FILL0_wght400_GRAD-25_opsz20.png"))); // NOI18N
        pnlMenuManageFlat.add(lblMenuManageFlatIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 54));

        lblMenuManageFlatTitle.setFont(new java.awt.Font("Poppins", 0, 28)); // NOI18N
        lblMenuManageFlatTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuManageFlatTitle.setText("Flat");
        pnlMenuManageFlat.add(lblMenuManageFlatTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 6, -1, -1));

        pnlMenu.add(pnlMenuManageFlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        pnlMenuManageTenant.setMaximumSize(new java.awt.Dimension(371, 60));
        pnlMenuManageTenant.setMinimumSize(new java.awt.Dimension(371, 60));
        pnlMenuManageTenant.setOpaque(false);
        pnlMenuManageTenant.setPreferredSize(new java.awt.Dimension(371, 60));
        pnlMenuManageTenant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenuManageTenantMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMenuManageTenantMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMenuManageTenantMouseExited(evt);
            }
        });
        pnlMenuManageTenant.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuManageTenantIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technoComplex/resources/image/icons/manage_accounts_16dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        pnlMenuManageTenant.add(lblMenuManageTenantIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 6, -1, 48));

        lblMenuManageTenantTitle.setFont(new java.awt.Font("Poppins", 0, 28)); // NOI18N
        lblMenuManageTenantTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuManageTenantTitle.setText("Tenant");
        pnlMenuManageTenant.add(lblMenuManageTenantTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 11, -1, -1));

        pnlMenu.add(pnlMenuManageTenant, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, -1, -1));

        lblMenuSortAndSearchLeftBoder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        pnlMenu.add(lblMenuSortAndSearchLeftBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 100, 10));

        lblMenuSortAndSearchTitle.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        lblMenuSortAndSearchTitle.setForeground(new java.awt.Color(191, 191, 191));
        lblMenuSortAndSearchTitle.setText("Sort and Search");
        pnlMenu.add(lblMenuSortAndSearchTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 160, 20));

        lblMenuSortAndSearchRightBoder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        pnlMenu.add(lblMenuSortAndSearchRightBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 120, 10));

        pnlMenuSortAndSearchFlat.setMaximumSize(new java.awt.Dimension(371, 60));
        pnlMenuSortAndSearchFlat.setMinimumSize(new java.awt.Dimension(371, 60));
        pnlMenuSortAndSearchFlat.setOpaque(false);
        pnlMenuSortAndSearchFlat.setPreferredSize(new java.awt.Dimension(371, 60));
        pnlMenuSortAndSearchFlat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenuSortAndSearchFlatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMenuSortAndSearchFlatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMenuSortAndSearchFlatMouseExited(evt);
            }
        });
        pnlMenuSortAndSearchFlat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuSortAndSearchFlatIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technoComplex/resources/image/icons/manage_search_16dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        pnlMenuSortAndSearchFlat.add(lblMenuSortAndSearchFlatIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 58, 51));

        lblMenuSortAndSearchFlatTitle.setFont(new java.awt.Font("Poppins", 0, 28)); // NOI18N
        lblMenuSortAndSearchFlatTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuSortAndSearchFlatTitle.setText("Flat");
        pnlMenuSortAndSearchFlat.add(lblMenuSortAndSearchFlatTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 8, -1, -1));

        pnlMenu.add(pnlMenuSortAndSearchFlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, -1, -1));

        pnlMenuSortAndSearchTenant.setMaximumSize(new java.awt.Dimension(371, 60));
        pnlMenuSortAndSearchTenant.setMinimumSize(new java.awt.Dimension(371, 60));
        pnlMenuSortAndSearchTenant.setOpaque(false);
        pnlMenuSortAndSearchTenant.setPreferredSize(new java.awt.Dimension(371, 60));
        pnlMenuSortAndSearchTenant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenuSortAndSearchTenantMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMenuSortAndSearchTenantMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMenuSortAndSearchTenantMouseExited(evt);
            }
        });
        pnlMenuSortAndSearchTenant.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuSortAndSearchTenantIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technoComplex/resources/image/icons/manage_search_16dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        pnlMenuSortAndSearchTenant.add(lblMenuSortAndSearchTenantIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 58, 51));

        lblMenuSortAndSearchTenantTitle.setFont(new java.awt.Font("Poppins", 0, 28)); // NOI18N
        lblMenuSortAndSearchTenantTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuSortAndSearchTenantTitle.setText("Tenant");
        pnlMenuSortAndSearchTenant.add(lblMenuSortAndSearchTenantTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 8, -1, -1));

        pnlMenu.add(pnlMenuSortAndSearchTenant, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, -1, -1));

        lblMenuSettingLeftBoder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        pnlMenu.add(lblMenuSettingLeftBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 130, 10));

        lblMenuSettingTitle.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        lblMenuSettingTitle.setForeground(new java.awt.Color(191, 191, 191));
        lblMenuSettingTitle.setText("Setting");
        pnlMenu.add(lblMenuSettingTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 610, 70, 20));

        lblMenuSettingRightBoder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        pnlMenu.add(lblMenuSettingRightBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 610, 160, 10));

        pnlMenuSettingLogout.setMaximumSize(new java.awt.Dimension(371, 60));
        pnlMenuSettingLogout.setMinimumSize(new java.awt.Dimension(371, 60));
        pnlMenuSettingLogout.setOpaque(false);
        pnlMenuSettingLogout.setPreferredSize(new java.awt.Dimension(371, 60));
        pnlMenuSettingLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenuSettingLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMenuSettingLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMenuSettingLogoutMouseExited(evt);
            }
        });
        pnlMenuSettingLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuSettingLogoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technoComplex/resources/image/icons/logout_16dp_FFFFFF_FILL0_wght400_GRAD0_opsz20.png"))); // NOI18N
        pnlMenuSettingLogout.add(lblMenuSettingLogoutIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 58, 50));

        lblMenuSettingLogoutTitle.setFont(new java.awt.Font("Poppins", 0, 28)); // NOI18N
        lblMenuSettingLogoutTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuSettingLogoutTitle.setText("Log Out");
        pnlMenuSettingLogout.add(lblMenuSettingLogoutTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 8, -1, -1));

        pnlMenu.add(pnlMenuSettingLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, -1, -1));

        lblMenuBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technoComplex/resources/image/background/fd.png"))); // NOI18N
        pnlMenu.add(lblMenuBackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlDashboardMain.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblLoginClose.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLoginClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technoComplex/resources/image/icons/close.png"))); // NOI18N
        lblLoginClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblLoginClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginCloseMouseClicked(evt);
            }
        });
        pnlDashboardMain.add(lblLoginClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 0, 50, 50));

        lblViewTenantDetails.setFont(new java.awt.Font("Poppins", 0, 34)); // NOI18N
        lblViewTenantDetails.setForeground(new java.awt.Color(102, 153, 255));
        lblViewTenantDetails.setText("View Tenant Details");
        pnlDashboardMain.add(lblViewTenantDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 620, 400, 40));

        scrlpnMangeTenantTable.setBackground(new java.awt.Color(0, 255, 204));
        scrlpnMangeTenantTable.setForeground(new java.awt.Color(255, 255, 255));
        scrlpnMangeTenantTable.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblMangeTenant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tenant Id", "Name", "Age", "Contact", "Join Date", "Flat Id", "Gender"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.String.class, java.lang.Short.class, java.lang.String.class, java.lang.String.class, java.lang.Short.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMangeTenant.getTableHeader().setReorderingAllowed(false);
        scrlpnMangeTenantTable.setViewportView(tblMangeTenant);

        pnlDashboardMain.add(scrlpnMangeTenantTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 670, 1210, 230));

        lblViewFlatDetails.setFont(new java.awt.Font("Poppins", 0, 34)); // NOI18N
        lblViewFlatDetails.setForeground(new java.awt.Color(102, 153, 255));
        lblViewFlatDetails.setText("View Flat Details");
        pnlDashboardMain.add(lblViewFlatDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 320, 40));

        scrlpnMangeFlatTable.setBackground(new java.awt.Color(0, 255, 204));
        scrlpnMangeFlatTable.setForeground(new java.awt.Color(255, 255, 255));
        scrlpnMangeFlatTable.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblMangeFlat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FlatId", "Price", "Size", "Livingroom", "Bedroom", "Kitchen", "Furnish", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Byte.class, java.lang.Byte.class, java.lang.Byte.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMangeFlat.getTableHeader().setReorderingAllowed(false);
        scrlpnMangeFlatTable.setViewportView(tblMangeFlat);

        pnlDashboardMain.add(scrlpnMangeFlatTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 1210, 220));

        lblCountOfRentedFlat.setFont(new java.awt.Font("Poppins", 0, 72)); // NOI18N
        lblCountOfRentedFlat.setForeground(new java.awt.Color(255, 255, 255));
        lblCountOfRentedFlat.setText("4");
        pnlDashboardMain.add(lblCountOfRentedFlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 180, 100));

        lblRentedFlatBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technoComplex/resources/image/background/Rented Flat.png"))); // NOI18N
        pnlDashboardMain.add(lblRentedFlatBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        lblAvailable.setFont(new java.awt.Font("Poppins", 0, 34)); // NOI18N
        lblAvailable.setForeground(new java.awt.Color(255, 255, 255));
        lblAvailable.setText("Available");
        pnlDashboardMain.add(lblAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 50, 170, 40));

        lblForRent.setFont(new java.awt.Font("Poppins", 0, 34)); // NOI18N
        lblForRent.setForeground(new java.awt.Color(255, 255, 255));
        lblForRent.setText("For Rent");
        pnlDashboardMain.add(lblForRent, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 90, 170, 40));

        lblCountOfAvailableRent.setFont(new java.awt.Font("Poppins", 0, 72)); // NOI18N
        lblCountOfAvailableRent.setForeground(new java.awt.Color(255, 255, 255));
        lblCountOfAvailableRent.setText("7");
        pnlDashboardMain.add(lblCountOfAvailableRent, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 130, 180, 100));

        lblAvailableForRentBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technoComplex/resources/image/background/Availabe Flat.png"))); // NOI18N
        pnlDashboardMain.add(lblAvailableForRentBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 40, -1, -1));

        lblTotal.setFont(new java.awt.Font("Poppins", 0, 34)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total");
        pnlDashboardMain.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 50, 170, 40));

        lblIncome.setFont(new java.awt.Font("Poppins", 0, 34)); // NOI18N
        lblIncome.setForeground(new java.awt.Color(255, 255, 255));
        lblIncome.setText("Income");
        pnlDashboardMain.add(lblIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 90, 170, 40));

        lblCountOfTotalIncome.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        lblCountOfTotalIncome.setForeground(new java.awt.Color(255, 255, 255));
        lblCountOfTotalIncome.setText("11,800,00");
        pnlDashboardMain.add(lblCountOfTotalIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 140, 180, 60));

        lblTotalIncomeBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technoComplex/resources/image/background/Total Income.png"))); // NOI18N
        pnlDashboardMain.add(lblTotalIncomeBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 40, -1, -1));

        getContentPane().add(pnlDashboardMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   /**
     * Populate both tables Rent and Tenant with their data
     */
    private void initializeData() {

        tenantList = new ArrayList<>();
        // Registering sample tenant
        registerTenant(new TenantModel((short) 101, "Ram Shrestha", (short) 25, "9812345670", "2019-03-15", (short) 101, "Male"));
        registerTenant(new TenantModel((short) 102, "Sita Pokherel", (short) 30, "9823456781", "2020-06-10", (short) 102, "Female"));
        registerTenant(new TenantModel((short) 103, "Hari Khadka", (short) 40, "9834567892", "2018-08-20", (short) 103, "Male"));
        registerTenant(new TenantModel((short) 104, "Gita Thapa", (short) 22, "9845678903", "2021-01-25", (short) 104, "Female"));
        registerTenant(new TenantModel((short) 105, "Krishna Lama", (short) 35, "9856789014", "2022-11-05", (short) 105, "Male"));
        registerTenant(new TenantModel((short) 106, "Rita Koirala", (short) 28, "9867890125", "2023-09-30", (short) 106, "Female"));
        registerTenant(new TenantModel((short) 107, "Bikash Kafle", (short) 45, "9878901236", "2024-07-18", (short) 107, "Male"));
        registerTenant(new TenantModel((short) 108, "Saraswati Rai", (short) 32, "9889012347", "2020-04-12", (short) 108, "Female"));
        registerTenant(new TenantModel((short) 109, "Prakash Karki", (short) 50, "9890123458", "2023-02-28", (short) 109, "Male"));
        registerTenant(new TenantModel((short) 110, "Mina Dahal", (short) 27, "9801234569", "2018-12-10", (short) 110, "Female"));

        flatList = new ArrayList<>();
        // Registering sample flat
        registerFlat(new FlatModel((short) 100, 25000, 500, (byte) 1, (byte) 1, (byte) 1, "Furnished", "Available"));
        registerFlat(new FlatModel((short) 101, 25000, 500, (byte) 1, (byte) 1, (byte) 1, "Furnished", "Available"));
        registerFlat(new FlatModel((short) 102, 150000, 800, (byte) 2, (byte) 2, (byte) 1, "Unfurnished", "Available"));
        registerFlat(new FlatModel((short) 103, 300000, 1200, (byte) 3, (byte) 4, (byte) 2, "Furnished", "Not Available"));
        registerFlat(new FlatModel((short) 104, 500000, 2000, (byte) 4, (byte) 5, (byte) 3, "Furnished", "Available"));
        registerFlat(new FlatModel((short) 105, 70000, 600, (byte) 2, (byte) 1, (byte) 1, "Unfurnished", "Available"));
        registerFlat(new FlatModel((short) 106, 120000, 900, (byte) 3, (byte) 3, (byte) 2, "Furnished", "Not Available"));
        registerFlat(new FlatModel((short) 107, 450000, 1800, (byte) 4, (byte) 5, (byte) 3, "Unfurnished", "Available"));
        registerFlat(new FlatModel((short) 108, 60000, 1200, (byte) 2, (byte) 1, (byte) 1, "Furnished", "Not Available"));
        registerFlat(new FlatModel((short) 109, 200000, 1500, (byte) 2, (byte) 4, (byte) 2, "Unfurnished", "Available"));
        registerFlat(new FlatModel((short) 110, 350000, 2200, (byte) 4, (byte) 6, (byte) 3, "Furnished", "Not Available"));
    }

    /**
     * Import the object data into the table row
     *
     * @param tenant the object of containing the details of tenants
     */
    private void registerTenant(TenantModel tenant) {
        tenantList.add(tenant);
        DefaultTableModel model = (DefaultTableModel) tblMangeTenant.getModel();
        model.addRow(new Object[]{
            tenant.getTenantId(), tenant.getName(), tenant.getAge(), tenant.getContact(),
            tenant.getJoinDate(), tenant.getFlatId(), tenant.getGender()
        });
    }

    /**
     * Import the object data into the table row
     *
     * @param flat the object of containing the details of flats
     */
    private void registerFlat(FlatModel flat) {
        flatList.add(flat);
        DefaultTableModel model = (DefaultTableModel) tblMangeFlat.getModel();
        model.addRow(new Object[]{
            flat.getFlatId(), flat.getPrice(), flat.getSize(), flat.getLivingroom(),
            flat.getBedroom(), flat.getKitchen(), flat.GetFurnising(), flat.GetFlatStatus()
        });
    }

    /**
     * Turn the background light and show underline for label when mouse entered
     * the menu item i.e hover effect
     *
     * @param menuPanel the menu item panel in which light background (hover
     * effect) is to be shown
     * @param menuPanelLabel the menu title label in which underline label
     * (hover effect) is to be shown
     */
    private void mouseEnter(JPanel menuPanel, JLabel menuPanelLabel) {
        menuPanel.setBackground(null);
        menuPanel.setBackground(new Color(192, 213, 255));
        menuPanel.setOpaque(true);
        menuPanelLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
    }

    /**
     * Remove the hover effect when mouse leave the menu item
     *
     * @param menuPanel the menu item panel to turn it back to normal
     * @param menuPanelLabel the menu title label to turn it back to normal
     *
     */
    private void mouseExit(JPanel menuPanel, JLabel menuPanelLabel) {
        menuPanel.setBackground(null);
        menuPanel.setOpaque(false);
        menuPanelLabel.setBorder(null);
    }
    private void pnlMenuManageFlatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuManageFlatMouseClicked
        new ManageFlat().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlMenuManageFlatMouseClicked

    private void pnlMenuManageFlatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuManageFlatMouseEntered
        mouseEnter(pnlMenuManageFlat, lblMenuManageFlatTitle);
    }//GEN-LAST:event_pnlMenuManageFlatMouseEntered

    private void pnlMenuManageFlatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuManageFlatMouseExited
        mouseExit(pnlMenuManageFlat, lblMenuManageFlatTitle);
    }//GEN-LAST:event_pnlMenuManageFlatMouseExited

    private void pnlMenuManageTenantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuManageTenantMouseClicked
        new ManageTenant().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlMenuManageTenantMouseClicked

    private void pnlMenuManageTenantMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuManageTenantMouseEntered
        mouseEnter(pnlMenuManageTenant, lblMenuManageTenantTitle);
    }//GEN-LAST:event_pnlMenuManageTenantMouseEntered

    private void pnlMenuManageTenantMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuManageTenantMouseExited
        mouseExit(pnlMenuManageTenant, lblMenuManageTenantTitle);
    }//GEN-LAST:event_pnlMenuManageTenantMouseExited

    private void pnlMenuSortAndSearchFlatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuSortAndSearchFlatMouseClicked
        new SortAndSearchFlat().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlMenuSortAndSearchFlatMouseClicked

    private void pnlMenuSortAndSearchFlatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuSortAndSearchFlatMouseEntered
        mouseEnter(pnlMenuSortAndSearchFlat, lblMenuSortAndSearchFlatTitle);
    }//GEN-LAST:event_pnlMenuSortAndSearchFlatMouseEntered

    private void pnlMenuSortAndSearchFlatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuSortAndSearchFlatMouseExited
        mouseExit(pnlMenuSortAndSearchFlat, lblMenuSortAndSearchFlatTitle);
    }//GEN-LAST:event_pnlMenuSortAndSearchFlatMouseExited

    private void pnlMenuSortAndSearchTenantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuSortAndSearchTenantMouseClicked
        new SortAndSearchTenant().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlMenuSortAndSearchTenantMouseClicked

    private void pnlMenuSortAndSearchTenantMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuSortAndSearchTenantMouseEntered
        mouseEnter(pnlMenuSortAndSearchTenant, lblMenuSortAndSearchTenantTitle);
    }//GEN-LAST:event_pnlMenuSortAndSearchTenantMouseEntered

    private void pnlMenuSortAndSearchTenantMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuSortAndSearchTenantMouseExited
        mouseExit(pnlMenuSortAndSearchTenant, lblMenuSortAndSearchTenantTitle);
    }//GEN-LAST:event_pnlMenuSortAndSearchTenantMouseExited

    private void pnlMenuSettingLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuSettingLogoutMouseClicked
        new LogIn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlMenuSettingLogoutMouseClicked

    private void pnlMenuSettingLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuSettingLogoutMouseEntered
        mouseEnter(pnlMenuSettingLogout, lblMenuSettingLogoutTitle);
    }//GEN-LAST:event_pnlMenuSettingLogoutMouseEntered

    private void pnlMenuSettingLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuSettingLogoutMouseExited
        mouseExit(pnlMenuSettingLogout, lblMenuSettingLogoutTitle);
    }//GEN-LAST:event_pnlMenuSettingLogoutMouseExited

    private void pnlMenuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuHomeMouseClicked
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlMenuHomeMouseClicked

    private void pnlMenuHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuHomeMouseEntered
        mouseEnter(pnlMenuHome, lblMenuHomeTitle);
    }//GEN-LAST:event_pnlMenuHomeMouseEntered

    private void pnlMenuHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuHomeMouseExited
        mouseExit(pnlMenuHome, lblMenuHomeTitle);
    }//GEN-LAST:event_pnlMenuHomeMouseExited
    /**
     * Handles the mouse click event on the close label in the dashboard window.
     * Prompts the user with a confirmation dialog to close the system. If the
     * user confirms, the application is terminated.
     *
     * @param evt the event triggered by clicking on the close label
     */
    private void lblLoginCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginCloseMouseClicked
        int closeSystem = JOptionPane.showConfirmDialog(pnlDashboardMain, "Do you want to close the \nTecnho Management System", "Close System", JOptionPane.YES_NO_OPTION);
        if (closeSystem == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_lblLoginCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAvailable;
    private javax.swing.JLabel lblAvailableForRentBackground;
    private javax.swing.JLabel lblCountOfAvailableRent;
    private javax.swing.JLabel lblCountOfRentedFlat;
    private javax.swing.JLabel lblCountOfTotalIncome;
    private javax.swing.JLabel lblForRent;
    private javax.swing.JLabel lblIncome;
    private javax.swing.JLabel lblLoginClose;
    private javax.swing.JLabel lblMenuBackgroundImage;
    private javax.swing.JLabel lblMenuDashboardIcon;
    private javax.swing.JLabel lblMenuDashboardTitle;
    private javax.swing.JLabel lblMenuHomeIcon;
    private javax.swing.JLabel lblMenuHomeTitle;
    private javax.swing.JLabel lblMenuManageFlatIcon;
    private javax.swing.JLabel lblMenuManageFlatTitle;
    private javax.swing.JLabel lblMenuManageLeftBoder;
    private javax.swing.JLabel lblMenuManageRightBoder;
    private javax.swing.JLabel lblMenuManageTenantIcon;
    private javax.swing.JLabel lblMenuManageTenantTitle;
    private javax.swing.JLabel lblMenuManageTitle;
    private javax.swing.JLabel lblMenuSettingLeftBoder;
    private javax.swing.JLabel lblMenuSettingLogoutIcon;
    private javax.swing.JLabel lblMenuSettingLogoutTitle;
    private javax.swing.JLabel lblMenuSettingRightBoder;
    private javax.swing.JLabel lblMenuSettingTitle;
    private javax.swing.JLabel lblMenuSortAndSearchFlatIcon;
    private javax.swing.JLabel lblMenuSortAndSearchFlatTitle;
    private javax.swing.JLabel lblMenuSortAndSearchLeftBoder;
    private javax.swing.JLabel lblMenuSortAndSearchRightBoder;
    private javax.swing.JLabel lblMenuSortAndSearchTenantIcon;
    private javax.swing.JLabel lblMenuSortAndSearchTenantTitle;
    private javax.swing.JLabel lblMenuSortAndSearchTitle;
    private javax.swing.JLabel lblMenuTitle;
    private javax.swing.JLabel lblMenuTitleBoder;
    private javax.swing.JLabel lblMenuTitleIcon;
    private javax.swing.JLabel lblRentedFlatBackground;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalIncomeBackground;
    private javax.swing.JLabel lblViewFlatDetails;
    private javax.swing.JLabel lblViewTenantDetails;
    private javax.swing.JPanel pnlDashboardMain;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlMenuDashboard;
    private javax.swing.JPanel pnlMenuHome;
    private javax.swing.JPanel pnlMenuManageFlat;
    private javax.swing.JPanel pnlMenuManageTenant;
    private javax.swing.JPanel pnlMenuSettingLogout;
    private javax.swing.JPanel pnlMenuSortAndSearchFlat;
    private javax.swing.JPanel pnlMenuSortAndSearchTenant;
    private javax.swing.JScrollPane scrlpnMangeFlatTable;
    private javax.swing.JScrollPane scrlpnMangeTenantTable;
    private javax.swing.JTable tblMangeFlat;
    private javax.swing.JTable tblMangeTenant;
    // End of variables declaration//GEN-END:variables
}
