/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.technocomplex.views;

import com.technocomplex.model.FlatModel;
import com.technocomplex.model.TenantModel;
import com.technocomplex.util.TableUtil;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * <b>The Dashboard show the record of flat and tenant in tabular format.
 * Dashboard also show the Number of available flat, Number of rented flat and
 * Total income generated monthly.</b>
 *
 * Features include:
 * <ul>
 * <li>Navigation to various screens</li>
 * <li>Record of flat and tenant in tabular format</li>
 * <li>Dynamically show the Number of available flat, Number of rented flat and
 * Total income generated monthly</li>
 * </ul>
 *
 * <p>
 * This class is initialized with default or user-provided flat and tenant
 * data.</P>
 *
 * @author prajwal Luitel LMU Id 23048626
 */
public class Dashboard extends javax.swing.JFrame {

    private List<TenantModel> tenantList;
    private List<FlatModel> flatList;

    /**
     * Creates new form Dashboard populate both tables with the data.
     */
    public Dashboard() {
        initComponents();
        flatList = TableUtil.initialFlatData(flatList);
        tenantList = TableUtil.initialTenantData(tenantList);
        displayDashboardNumber();
        TableUtil.designTable(tblFlat);
        TableUtil.designTable(tblTenant);
        TableUtil.loadListDataToTable(flatList, tblFlat);
        TableUtil.loadListDataToTable(tenantList, tblTenant);
    }

    /**
     * Creates new form Dashboard populate both tables with the data obtained
     * from other JFrame
     *
     * @param flatList flat data list from other JFrame
     * @param tenantList tenant data list from other JFrame
     */
    public Dashboard(List<FlatModel> flatList, List<TenantModel> tenantList) {
        initComponents();
        this.flatList = new ArrayList<>(flatList);
        this.tenantList = new ArrayList<>(tenantList);
        displayDashboardNumber();
        TableUtil.designTable(tblFlat);
        TableUtil.designTable(tblTenant);
        TableUtil.loadListDataToTable(flatList, tblFlat);
        TableUtil.loadListDataToTable(tenantList, tblTenant);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDashboardMain = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        lblMenuTitleIcon = new javax.swing.JLabel();
        lblMenuTitle = new javax.swing.JLabel();
        lblMenuTitleBoder = new javax.swing.JLabel();
        pnlMenuHome = new javax.swing.JPanel();
        lblMenuHomeIcon = new javax.swing.JLabel();
        lblMenuHomeTitle = new javax.swing.JLabel();
        pnlMenuDashboard = new javax.swing.JPanel();
        lblMenuDashboardIcon = new javax.swing.JLabel();
        lblMenuDashboardTitle = new javax.swing.JLabel();
        lblMenuManageLeftBoder = new javax.swing.JLabel();
        lblMenuManageTitle = new javax.swing.JLabel();
        lblMenuManageRightBoder = new javax.swing.JLabel();
        pnlMenuManageFlat = new javax.swing.JPanel();
        lblMenuManageFlatIcon = new javax.swing.JLabel();
        lblMenuManageFlatTitle = new javax.swing.JLabel();
        pnlMenuManageTenant = new javax.swing.JPanel();
        lblMenuManageTenantIcon = new javax.swing.JLabel();
        lblMenuManageTenantTitle = new javax.swing.JLabel();
        lblMenuSortAndSearchLeftBoder = new javax.swing.JLabel();
        lblMenuSortAndSearchTitle = new javax.swing.JLabel();
        lblMenuSortAndSearchRightBoder = new javax.swing.JLabel();
        pnlMenuSortAndSearchFlat = new javax.swing.JPanel();
        lblMenuSortAndSearchFlatIcon = new javax.swing.JLabel();
        lblMenuSortAndSearchFlatTitle = new javax.swing.JLabel();
        pnlMenuSortAndSearchTenant = new javax.swing.JPanel();
        lblMenuSortAndSearchTenantIcon = new javax.swing.JLabel();
        lblMenuSortAndSearchTenantTitle = new javax.swing.JLabel();
        lblMenuSettingLeftBoder = new javax.swing.JLabel();
        lblMenuSettingTitle = new javax.swing.JLabel();
        lblMenuSettingRightBoder = new javax.swing.JLabel();
        pnlMenuSettingLogout = new javax.swing.JPanel();
        lblMenuSettingLogoutIcon = new javax.swing.JLabel();
        lblMenuSettingLogoutTitle = new javax.swing.JLabel();
        pnlMenuManageCleaningLog = new javax.swing.JPanel();
        lblMenuManageCleaningLogIcon = new javax.swing.JLabel();
        lblMenuManageCleaningLog = new javax.swing.JLabel();
        lblMenuBackgroundImage = new javax.swing.JLabel();
        lblLoginClose = new javax.swing.JLabel();
        lblViewTenantDetails = new javax.swing.JLabel();
        scrlpnTenant = new javax.swing.JScrollPane();
        tblTenant = new javax.swing.JTable();
        lblViewFlatDetails = new javax.swing.JLabel();
        scrlpnFlat = new javax.swing.JScrollPane();
        tblFlat = new javax.swing.JTable();
        lblCountOfRentedFlat = new javax.swing.JLabel();
        lblRented = new javax.swing.JLabel();
        lblFlat = new javax.swing.JLabel();
        lblRentedFlatBackground = new javax.swing.JLabel();
        lblAvailable = new javax.swing.JLabel();
        lblForRent = new javax.swing.JLabel();
        lblCountOfAvailableRent = new javax.swing.JLabel();
        lblAvailableForRentBackground = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblIncome = new javax.swing.JLabel();
        lblCountOfTotalIncome = new javax.swing.JLabel();
        lblTotalIncomeBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1706, 912));
        setName("Dashboard"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1706, 912));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDashboardMain.setBackground(new java.awt.Color(232, 245, 255));
        pnlDashboardMain.setMaximumSize(new java.awt.Dimension(1706, 912));
        pnlDashboardMain.setMinimumSize(new java.awt.Dimension(1706, 912));
        pnlDashboardMain.setPreferredSize(new java.awt.Dimension(1706, 912));
        pnlDashboardMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenu.setMaximumSize(new java.awt.Dimension(371, 912));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuTitleIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/icons/Techno Complex White  Logo.png"))); // NOI18N
        pnlMenu.add(lblMenuTitleIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 10, 220, 150));

        lblMenuTitle.setFont(new java.awt.Font("Poppins", 2, 26)); // NOI18N
        lblMenuTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuTitle.setText("Techno Complex");
        pnlMenu.add(lblMenuTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 230, 80));

        lblMenuTitleBoder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        pnlMenu.add(lblMenuTitleBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 370, 60));

        pnlMenuHome.setMaximumSize(new java.awt.Dimension(371, 60));
        pnlMenuHome.setMinimumSize(new java.awt.Dimension(371, 60));
        pnlMenuHome.setOpaque(false);
        pnlMenuHome.setPreferredSize(new java.awt.Dimension(371, 60));
        pnlMenuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenuHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMenuHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMenuHomeMouseExited(evt);
            }
        });
        pnlMenuHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuHomeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/icons/Home.png"))); // NOI18N
        lblMenuHomeIcon.setToolTipText("");
        pnlMenuHome.add(lblMenuHomeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 70, 50));

        lblMenuHomeTitle.setFont(new java.awt.Font("Poppins", 0, 28)); // NOI18N
        lblMenuHomeTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuHomeTitle.setText("Home");
        pnlMenuHome.add(lblMenuHomeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        pnlMenu.add(pnlMenuHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        pnlMenuDashboard.setBackground(new java.awt.Color(97,97,97,120));
        pnlMenuDashboard.setMaximumSize(new java.awt.Dimension(371, 60));
        pnlMenuDashboard.setMinimumSize(new java.awt.Dimension(371, 60));
        pnlMenuDashboard.setPreferredSize(new java.awt.Dimension(371, 60));
        pnlMenuDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuDashboardIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/icons/Dashboard.png"))); // NOI18N
        pnlMenuDashboard.add(lblMenuDashboardIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 6, -1, 48));

        lblMenuDashboardTitle.setFont(new java.awt.Font("Poppins", 0, 28)); // NOI18N
        lblMenuDashboardTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuDashboardTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuDashboardTitle.setText("Dashboard");
        pnlMenuDashboard.add(lblMenuDashboardTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 6, -1, -1));

        pnlMenu.add(pnlMenuDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        lblMenuManageLeftBoder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        pnlMenu.add(lblMenuManageLeftBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 130, 10));

        lblMenuManageTitle.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblMenuManageTitle.setForeground(new java.awt.Color(191, 191, 191));
        lblMenuManageTitle.setText("Manage");
        pnlMenu.add(lblMenuManageTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 90, 20));

        lblMenuManageRightBoder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        pnlMenu.add(lblMenuManageRightBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 150, 10));

        pnlMenuManageFlat.setMaximumSize(new java.awt.Dimension(371, 60));
        pnlMenuManageFlat.setMinimumSize(new java.awt.Dimension(371, 60));
        pnlMenuManageFlat.setOpaque(false);
        pnlMenuManageFlat.setPreferredSize(new java.awt.Dimension(371, 60));
        pnlMenuManageFlat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenuManageFlatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMenuManageFlatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMenuManageFlatMouseExited(evt);
            }
        });
        pnlMenuManageFlat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuManageFlatIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/icons/Manage Flat.png"))); // NOI18N
        pnlMenuManageFlat.add(lblMenuManageFlatIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 54));

        lblMenuManageFlatTitle.setFont(new java.awt.Font("Poppins", 0, 28)); // NOI18N
        lblMenuManageFlatTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuManageFlatTitle.setText("Flat");
        pnlMenuManageFlat.add(lblMenuManageFlatTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 6, -1, -1));

        pnlMenu.add(pnlMenuManageFlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        pnlMenuManageTenant.setMaximumSize(new java.awt.Dimension(371, 60));
        pnlMenuManageTenant.setMinimumSize(new java.awt.Dimension(371, 60));
        pnlMenuManageTenant.setOpaque(false);
        pnlMenuManageTenant.setPreferredSize(new java.awt.Dimension(371, 60));
        pnlMenuManageTenant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenuManageTenantMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMenuManageTenantMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMenuManageTenantMouseExited(evt);
            }
        });
        pnlMenuManageTenant.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuManageTenantIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/icons/Manage Tenant.png"))); // NOI18N
        pnlMenuManageTenant.add(lblMenuManageTenantIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 6, -1, 48));

        lblMenuManageTenantTitle.setFont(new java.awt.Font("Poppins", 0, 28)); // NOI18N
        lblMenuManageTenantTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuManageTenantTitle.setText("Tenant");
        pnlMenuManageTenant.add(lblMenuManageTenantTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 11, -1, -1));

        pnlMenu.add(pnlMenuManageTenant, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, -1, -1));

        lblMenuSortAndSearchLeftBoder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        pnlMenu.add(lblMenuSortAndSearchLeftBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 100, 10));

        lblMenuSortAndSearchTitle.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        lblMenuSortAndSearchTitle.setForeground(new java.awt.Color(191, 191, 191));
        lblMenuSortAndSearchTitle.setText("Sort and Search");
        pnlMenu.add(lblMenuSortAndSearchTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 160, 20));

        lblMenuSortAndSearchRightBoder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        pnlMenu.add(lblMenuSortAndSearchRightBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 120, 10));

        pnlMenuSortAndSearchFlat.setMaximumSize(new java.awt.Dimension(371, 60));
        pnlMenuSortAndSearchFlat.setMinimumSize(new java.awt.Dimension(371, 60));
        pnlMenuSortAndSearchFlat.setOpaque(false);
        pnlMenuSortAndSearchFlat.setPreferredSize(new java.awt.Dimension(371, 60));
        pnlMenuSortAndSearchFlat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenuSortAndSearchFlatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMenuSortAndSearchFlatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMenuSortAndSearchFlatMouseExited(evt);
            }
        });
        pnlMenuSortAndSearchFlat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuSortAndSearchFlatIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/icons/Sort and Search.png"))); // NOI18N
        pnlMenuSortAndSearchFlat.add(lblMenuSortAndSearchFlatIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 58, 51));

        lblMenuSortAndSearchFlatTitle.setFont(new java.awt.Font("Poppins", 0, 28)); // NOI18N
        lblMenuSortAndSearchFlatTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuSortAndSearchFlatTitle.setText("Flat");
        pnlMenuSortAndSearchFlat.add(lblMenuSortAndSearchFlatTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 8, -1, -1));

        pnlMenu.add(pnlMenuSortAndSearchFlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, -1, -1));

        pnlMenuSortAndSearchTenant.setMaximumSize(new java.awt.Dimension(371, 60));
        pnlMenuSortAndSearchTenant.setMinimumSize(new java.awt.Dimension(371, 60));
        pnlMenuSortAndSearchTenant.setOpaque(false);
        pnlMenuSortAndSearchTenant.setPreferredSize(new java.awt.Dimension(371, 60));
        pnlMenuSortAndSearchTenant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenuSortAndSearchTenantMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMenuSortAndSearchTenantMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMenuSortAndSearchTenantMouseExited(evt);
            }
        });
        pnlMenuSortAndSearchTenant.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuSortAndSearchTenantIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/icons/Sort and Search.png"))); // NOI18N
        pnlMenuSortAndSearchTenant.add(lblMenuSortAndSearchTenantIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 58, 51));

        lblMenuSortAndSearchTenantTitle.setFont(new java.awt.Font("Poppins", 0, 28)); // NOI18N
        lblMenuSortAndSearchTenantTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuSortAndSearchTenantTitle.setText("Tenant");
        pnlMenuSortAndSearchTenant.add(lblMenuSortAndSearchTenantTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 8, -1, -1));

        pnlMenu.add(pnlMenuSortAndSearchTenant, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, -1, -1));

        lblMenuSettingLeftBoder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        pnlMenu.add(lblMenuSettingLeftBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 130, 10));

        lblMenuSettingTitle.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        lblMenuSettingTitle.setForeground(new java.awt.Color(191, 191, 191));
        lblMenuSettingTitle.setText("Setting");
        pnlMenu.add(lblMenuSettingTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 670, 70, 20));

        lblMenuSettingRightBoder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        pnlMenu.add(lblMenuSettingRightBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 670, 160, 10));

        pnlMenuSettingLogout.setMaximumSize(new java.awt.Dimension(371, 60));
        pnlMenuSettingLogout.setMinimumSize(new java.awt.Dimension(371, 60));
        pnlMenuSettingLogout.setOpaque(false);
        pnlMenuSettingLogout.setPreferredSize(new java.awt.Dimension(371, 60));
        pnlMenuSettingLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenuSettingLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMenuSettingLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMenuSettingLogoutMouseExited(evt);
            }
        });
        pnlMenuSettingLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuSettingLogoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/icons/Log Out.png"))); // NOI18N
        pnlMenuSettingLogout.add(lblMenuSettingLogoutIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 58, 50));

        lblMenuSettingLogoutTitle.setFont(new java.awt.Font("Poppins", 0, 28)); // NOI18N
        lblMenuSettingLogoutTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuSettingLogoutTitle.setText("Log Out");
        pnlMenuSettingLogout.add(lblMenuSettingLogoutTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 8, -1, -1));

        pnlMenu.add(pnlMenuSettingLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, -1, -1));

        pnlMenuManageCleaningLog.setMinimumSize(new java.awt.Dimension(371, 60));
        pnlMenuManageCleaningLog.setOpaque(false);
        pnlMenuManageCleaningLog.setPreferredSize(new java.awt.Dimension(371, 60));
        pnlMenuManageCleaningLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenuManageCleaningLogMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMenuManageCleaningLogMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMenuManageCleaningLogMouseExited(evt);
            }
        });
        pnlMenuManageCleaningLog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuManageCleaningLogIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/icons/Cleaning Log.png"))); // NOI18N
        pnlMenuManageCleaningLog.add(lblMenuManageCleaningLogIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 60));

        lblMenuManageCleaningLog.setFont(new java.awt.Font("Poppins", 0, 28)); // NOI18N
        lblMenuManageCleaningLog.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuManageCleaningLog.setText("Cleaning Log");
        pnlMenuManageCleaningLog.add(lblMenuManageCleaningLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 11, -1, -1));

        pnlMenu.add(pnlMenuManageCleaningLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, -1, -1));

        lblMenuBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/background/Menu.png"))); // NOI18N
        pnlMenu.add(lblMenuBackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlDashboardMain.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblLoginClose.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLoginClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/icons/Close.png"))); // NOI18N
        lblLoginClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblLoginClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginCloseMouseClicked(evt);
            }
        });
        pnlDashboardMain.add(lblLoginClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 0, 50, 50));

        lblViewTenantDetails.setFont(new java.awt.Font("Poppins", 0, 34)); // NOI18N
        lblViewTenantDetails.setForeground(new java.awt.Color(102, 153, 255));
        lblViewTenantDetails.setText("View Tenant Details");
        pnlDashboardMain.add(lblViewTenantDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 620, 400, 40));

        scrlpnTenant.setBackground(new java.awt.Color(0, 255, 204));
        scrlpnTenant.setForeground(new java.awt.Color(255, 255, 255));
        scrlpnTenant.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblTenant.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tblTenant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tenant Id", "Name", "Age", "Contact", "Join Date", "Flat Id", "Gender"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.String.class, java.lang.Short.class, java.lang.String.class, java.lang.String.class, java.lang.Short.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTenant.setRowHeight(30);
        tblTenant.getTableHeader().setReorderingAllowed(false);
        scrlpnTenant.setViewportView(tblTenant);
        if (tblTenant.getColumnModel().getColumnCount() > 0) {
            tblTenant.getColumnModel().getColumn(0).setResizable(false);
            tblTenant.getColumnModel().getColumn(1).setResizable(false);
            tblTenant.getColumnModel().getColumn(3).setResizable(false);
            tblTenant.getColumnModel().getColumn(5).setResizable(false);
            tblTenant.getColumnModel().getColumn(6).setResizable(false);
        }

        pnlDashboardMain.add(scrlpnTenant, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 670, 1210, 230));

        lblViewFlatDetails.setFont(new java.awt.Font("Poppins", 0, 34)); // NOI18N
        lblViewFlatDetails.setForeground(new java.awt.Color(102, 153, 255));
        lblViewFlatDetails.setText("View Flat Details");
        pnlDashboardMain.add(lblViewFlatDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 310, 320, 40));

        scrlpnFlat.setBackground(new java.awt.Color(0, 255, 204));
        scrlpnFlat.setForeground(new java.awt.Color(255, 255, 255));
        scrlpnFlat.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblFlat.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tblFlat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FlatId", "Price", "Size", "Livingroom", "Bedroom", "Kitchen", "Furnish", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Byte.class, java.lang.Byte.class, java.lang.Byte.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFlat.setGridColor(new java.awt.Color(0, 0, 0));
        tblFlat.setRowHeight(30);
        tblFlat.setShowGrid(false);
        tblFlat.getTableHeader().setReorderingAllowed(false);
        scrlpnFlat.setViewportView(tblFlat);
        if (tblFlat.getColumnModel().getColumnCount() > 0) {
            tblFlat.getColumnModel().getColumn(0).setResizable(false);
            tblFlat.getColumnModel().getColumn(1).setResizable(false);
            tblFlat.getColumnModel().getColumn(2).setResizable(false);
            tblFlat.getColumnModel().getColumn(3).setResizable(false);
            tblFlat.getColumnModel().getColumn(4).setResizable(false);
            tblFlat.getColumnModel().getColumn(5).setResizable(false);
            tblFlat.getColumnModel().getColumn(6).setResizable(false);
            tblFlat.getColumnModel().getColumn(7).setResizable(false);
        }

        pnlDashboardMain.add(scrlpnFlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 1210, 220));

        lblCountOfRentedFlat.setFont(new java.awt.Font("Poppins", 0, 72)); // NOI18N
        lblCountOfRentedFlat.setForeground(new java.awt.Color(255, 255, 255));
        lblCountOfRentedFlat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCountOfRentedFlat.setText("4");
        pnlDashboardMain.add(lblCountOfRentedFlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 180, 60));

        lblRented.setFont(new java.awt.Font("Poppins", 0, 34)); // NOI18N
        lblRented.setForeground(new java.awt.Color(255, 255, 255));
        lblRented.setText("Rented");
        pnlDashboardMain.add(lblRented, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 170, 40));

        lblFlat.setFont(new java.awt.Font("Poppins", 0, 34)); // NOI18N
        lblFlat.setForeground(new java.awt.Color(255, 255, 255));
        lblFlat.setText("Flat");
        pnlDashboardMain.add(lblFlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 170, 40));

        lblRentedFlatBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/background/Rented Flat.png"))); // NOI18N
        pnlDashboardMain.add(lblRentedFlatBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        lblAvailable.setFont(new java.awt.Font("Poppins", 0, 34)); // NOI18N
        lblAvailable.setForeground(new java.awt.Color(255, 255, 255));
        lblAvailable.setText("Available");
        pnlDashboardMain.add(lblAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 50, 170, 40));

        lblForRent.setFont(new java.awt.Font("Poppins", 0, 34)); // NOI18N
        lblForRent.setForeground(new java.awt.Color(255, 255, 255));
        lblForRent.setText("For Rent");
        pnlDashboardMain.add(lblForRent, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 90, 170, 40));

        lblCountOfAvailableRent.setFont(new java.awt.Font("Poppins", 0, 72)); // NOI18N
        lblCountOfAvailableRent.setForeground(new java.awt.Color(255, 255, 255));
        lblCountOfAvailableRent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCountOfAvailableRent.setText("7");
        pnlDashboardMain.add(lblCountOfAvailableRent, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 130, 180, 100));

        lblAvailableForRentBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/background/Available For Rent .png"))); // NOI18N
        pnlDashboardMain.add(lblAvailableForRentBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, -1, -1));

        lblTotal.setFont(new java.awt.Font("Poppins", 0, 34)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total");
        pnlDashboardMain.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 50, 170, 40));

        lblIncome.setFont(new java.awt.Font("Poppins", 0, 34)); // NOI18N
        lblIncome.setForeground(new java.awt.Color(255, 255, 255));
        lblIncome.setText("Income");
        pnlDashboardMain.add(lblIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 90, 170, 40));

        lblCountOfTotalIncome.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        lblCountOfTotalIncome.setForeground(new java.awt.Color(255, 255, 255));
        lblCountOfTotalIncome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCountOfTotalIncome.setText("11.8M");
        pnlDashboardMain.add(lblCountOfTotalIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 150, 230, 60));

        lblTotalIncomeBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/background/Total Income.png"))); // NOI18N
        pnlDashboardMain.add(lblTotalIncomeBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 40, -1, -1));

        getContentPane().add(pnlDashboardMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Turn the background light and show underline for label when mouse entered
     * the menu item i.e hover effect
     *
     * @param menuPanel the menu item panel in which light background (hover
     * effect) is to be shown
     * @param menuPanelLabel the menu title label in which underline label
     * (hover effect) is to be shown
     */
    private void mouseEnter(JPanel menuPanel, JLabel menuPanelLabel) {
        menuPanel.setBackground(null);
        menuPanel.setBackground(new Color(192, 213, 255));
        menuPanel.setOpaque(true);
        menuPanelLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
    }

    /**
     * Remove the hover effect when mouse leave the menu item
     *
     * @param menuPanel the menu item panel to turn it back to normal
     * @param menuPanelLabel the menu title label to turn it back to normal
     *
     */
    private void mouseExit(JPanel menuPanel, JLabel menuPanelLabel) {
        menuPanel.setBackground(null);
        menuPanel.setOpaque(false);
        menuPanelLabel.setBorder(null);
    }

    /**
     * Handles the mouse click event on the Menu Manage Flat panel. Direct the
     * user to Manage Flat screen and dispose this screen.
     *
     * @param evt the event triggered by clicking on the Menu Manage Flat panel
     */
    private void pnlMenuManageFlatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuManageFlatMouseClicked
        new ManageFlat(flatList, tenantList).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlMenuManageFlatMouseClicked

    /**
     * Handles the mouse Enter event on the Menu Manage Flat panel. Hover effect
     * on Menu Manage Flat panel is created.
     *
     * @param evt the event triggered by entering on the Menu Manage Flat panel.
     */
    private void pnlMenuManageFlatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuManageFlatMouseEntered
        mouseEnter(pnlMenuManageFlat, lblMenuManageFlatTitle);
    }//GEN-LAST:event_pnlMenuManageFlatMouseEntered

    /**
     * Handles the mouse Exit event on the Menu Manage Flat panel. Menu Manage
     * Flat panel is turned back to normal by removing hover effect.
     *
     * @param evt the event triggered by exiting on the Menu Manage Flat panel.
     */
    private void pnlMenuManageFlatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuManageFlatMouseExited
        mouseExit(pnlMenuManageFlat, lblMenuManageFlatTitle);
    }//GEN-LAST:event_pnlMenuManageFlatMouseExited

    /**
     * Handles the mouse click event on the Menu Manage Tenant. Direct the user
     * to Manage Tenant screen and dispose this screen.
     *
     * @param evt the event triggered by clicking on the Menu Manage Tenant
     * panel
     */
    private void pnlMenuManageTenantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuManageTenantMouseClicked
        new ManageTenant(flatList, tenantList).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlMenuManageTenantMouseClicked

    /**
     * Handles the mouse Enter event on the Menu Manage Tenant panel. Hover
     * effect on Menu Manage Tenant panel is created.
     *
     * @param evt the event triggered by entering on the Menu Manage Tenant
     * panel.
     */
    private void pnlMenuManageTenantMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuManageTenantMouseEntered
        mouseEnter(pnlMenuManageTenant, lblMenuManageTenantTitle);
    }//GEN-LAST:event_pnlMenuManageTenantMouseEntered

    /**
     * Handles the mouse Exit event on the Menu Manage Tenant panel. Menu Manage
     * Tenant panel is turned back to normal by removing hover effect.
     *
     * @param evt the event triggered by exiting on the Menu Manage Tenant
     * panel.
     */
    private void pnlMenuManageTenantMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuManageTenantMouseExited
        mouseExit(pnlMenuManageTenant, lblMenuManageTenantTitle);
    }//GEN-LAST:event_pnlMenuManageTenantMouseExited

    /**
     * Handles the mouse click event on the Menu Cleaning Log panel. Direct the
     * user to Cleaning Log screen and dispose this screen.
     *
     * @param evt the event triggered by clicking on the Menu Cleaning Log panel
     */
    private void pnlMenuManageCleaningLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuManageCleaningLogMouseClicked
        new CleaningLog(flatList, tenantList).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlMenuManageCleaningLogMouseClicked

    /**
     * Handles the mouse Enter event on the Menu Cleaning Log panel. Hover
     * effect on Menu Cleaning Log panel is created.
     *
     * @param evt the event triggered by entering on the Menu Cleaning Log
     * panel.
     */
    private void pnlMenuManageCleaningLogMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuManageCleaningLogMouseEntered
        mouseEnter(pnlMenuManageCleaningLog, lblMenuManageCleaningLog);
    }//GEN-LAST:event_pnlMenuManageCleaningLogMouseEntered

    /**
     * Handles the mouse Exit event on the Menu Cleaning Log panel. Menu
     * Cleaning Log panel is turned back to normal by removing hover effect.
     *
     * @param evt the event triggered by exiting on the Menu Cleaning Log panel.
     */
    private void pnlMenuManageCleaningLogMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuManageCleaningLogMouseExited
        mouseExit(pnlMenuManageCleaningLog, lblMenuManageCleaningLog);
    }//GEN-LAST:event_pnlMenuManageCleaningLogMouseExited

    /**
     * Handles the mouse click event on the Menu Sort and Search Flat panel.
     * Direct the user to Sort and Search Flat screen and dispose this screen.
     *
     * @param evt the event triggered by clicking on the Menu Sort and Search
     * Flat panel
     */
    private void pnlMenuSortAndSearchFlatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuSortAndSearchFlatMouseClicked
        new SortAndSearchFlat(flatList, tenantList).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlMenuSortAndSearchFlatMouseClicked

    /**
     * Handles the mouse Enter event on the Menu Sort and Search Flat panel.
     * Hover effect on Menu Sort and Search Flat panel is created.
     *
     * @param evt the event triggered by entering on the Menu Sort and Search
     * Flat panel.
     */
    private void pnlMenuSortAndSearchFlatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuSortAndSearchFlatMouseEntered
        mouseEnter(pnlMenuSortAndSearchFlat, lblMenuSortAndSearchFlatTitle);
    }//GEN-LAST:event_pnlMenuSortAndSearchFlatMouseEntered

    /**
     * Handles the mouse Exit event on the Menu Sort and Search Flat panel. Menu
     * Sort and Search Flat panel is turned back to normal by removing hover
     * effect.
     *
     * @param evt the event triggered by exiting on the Menu Sort and Search
     * Flat panel.
     */
    private void pnlMenuSortAndSearchFlatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuSortAndSearchFlatMouseExited
        mouseExit(pnlMenuSortAndSearchFlat, lblMenuSortAndSearchFlatTitle);
    }//GEN-LAST:event_pnlMenuSortAndSearchFlatMouseExited

    /**
     * Handles the mouse click event on the Menu Sort and Search Tenant panel.
     * Direct the user to Sort and Search Tenant screen and dispose this screen.
     *
     * @param evt the event triggered by clicking on the Menu Sort and Search
     * Tenant panel
     */
    private void pnlMenuSortAndSearchTenantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuSortAndSearchTenantMouseClicked
        new SortAndSearchTenant(flatList, tenantList).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlMenuSortAndSearchTenantMouseClicked

    /**
     * Handles the mouse Enter event on the Menu Sort and Search Tenant panel.
     * Hover effect on Menu Sort and Search Tenant panel is created.
     *
     * @param evt the event triggered by entering on the Menu Sort and Search
     * Tenant panel.
     */
    private void pnlMenuSortAndSearchTenantMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuSortAndSearchTenantMouseEntered
        mouseEnter(pnlMenuSortAndSearchTenant, lblMenuSortAndSearchTenantTitle);
    }//GEN-LAST:event_pnlMenuSortAndSearchTenantMouseEntered

    /**
     * Handles the mouse Exit event on the Menu Sort and Search Tenant panel.
     * Menu Sort and Search Tenant panel is turned back to normal by removing
     * hover effect.
     *
     * @param evt the event triggered by exiting on the Menu Sort and Search
     * Tenant panel.
     */
    private void pnlMenuSortAndSearchTenantMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuSortAndSearchTenantMouseExited
        mouseExit(pnlMenuSortAndSearchTenant, lblMenuSortAndSearchTenantTitle);
    }//GEN-LAST:event_pnlMenuSortAndSearchTenantMouseExited

    /**
     * Handles the mouse click event on the Menu Log Out panel. Direct the user
     * to Log In screen and dispose this screen.
     *
     * @param evt the event triggered by clicking on the Menu Log Out panel
     */
    private void pnlMenuSettingLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuSettingLogoutMouseClicked
        new LogIn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlMenuSettingLogoutMouseClicked

    /**
     * Handles the mouse Enter event on the Menu Log Out panel. Hover effect on
     * Menu Log Out panel is created.
     *
     * @param evt the event triggered by entering on the Menu Log Out panel.
     */
    private void pnlMenuSettingLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuSettingLogoutMouseEntered
        mouseEnter(pnlMenuSettingLogout, lblMenuSettingLogoutTitle);
    }//GEN-LAST:event_pnlMenuSettingLogoutMouseEntered

    /**
     * Handles the mouse Exit event on the Menu Log Out panel. Menu Log Out
     * panel is turned back to normal by removing hover effect.
     *
     * @param evt the event triggered by exiting on the Menu Log Out panel.
     */
    private void pnlMenuSettingLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuSettingLogoutMouseExited
        mouseExit(pnlMenuSettingLogout, lblMenuSettingLogoutTitle);
    }//GEN-LAST:event_pnlMenuSettingLogoutMouseExited

    /**
     * Handles the mouse click event on the Menu Home panel. Direct the user to
     * Home screen and dispose this screen.
     *
     * @param evt the event triggered by clicking on the Menu Home panel
     */
    private void pnlMenuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuHomeMouseClicked
        new Home(flatList, tenantList).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlMenuHomeMouseClicked

    /**
     * Handles the mouse Enter event on the Menu Home panel. Hover effect on
     * Menu Home panel is created.
     *
     * @param evt the event triggered by entering on the Menu Home panel.
     */
    private void pnlMenuHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuHomeMouseEntered
        mouseEnter(pnlMenuHome, lblMenuHomeTitle);
    }//GEN-LAST:event_pnlMenuHomeMouseEntered

    /**
     * Handles the mouse Exit event on the Menu Home panel. Menu Home panel is
     * turned back to normal by removing hover effect.
     *
     * @param evt the event triggered by exiting on the Menu Home panel.
     */
    private void pnlMenuHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuHomeMouseExited
        mouseExit(pnlMenuHome, lblMenuHomeTitle);
    }//GEN-LAST:event_pnlMenuHomeMouseExited

    /**
     * Handles the mouse click event on the close label in the dashboard window.
     * Prompts the user with a confirmation dialog to close the system. If the
     * user confirms, the application is terminated.
     *
     * @param evt the event triggered by clicking on the close label
     */
    private void lblLoginCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginCloseMouseClicked
        int closeSystem = JOptionPane.showConfirmDialog(pnlDashboardMain, "Do you want to close the \nTecnho Management System", "Close System", JOptionPane.YES_NO_OPTION);
        if (closeSystem == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_lblLoginCloseMouseClicked

    /**
     * Display the Number of rented flat, Number of available rent and total
     * income dynamically.
     */
    private void displayDashboardNumber() {
        int availableForFlat = 0;
        int totalIncome = 0;
        int rentedFlat = tenantList.size();
        for (FlatModel flat : flatList) {
            if (flat.getFlatStatus().equals("Available")) {
                ++availableForFlat;
            } else {
                totalIncome += flat.getPrice();
            }
        }
        String shortHandIncome = shortHandNumber(totalIncome);
        lblCountOfRentedFlat.setText(Integer.toString(rentedFlat));
        lblCountOfAvailableRent.setText(Integer.toString(availableForFlat));
        lblCountOfTotalIncome.setText(shortHandIncome);
    }

    /**
     * Convert the Number to Short Number by replacing 1000000 with M and 1000
     * with k.
     *
     * @param income which is to be converted
     * @return converted income
     */
    private String shortHandNumber(int income) {
        String shortHandNumber;
        if (income >= 1000000) {
            double roundedIncome = Math.round(income / 10000.0) / 100.0; // round off the million income upto 2 digit in decimal
            shortHandNumber = roundedIncome + "M";
        } else if (income >= 1000) {
            income = Math.round(income / 1000);
            shortHandNumber = income + "K";
        } else {
            shortHandNumber = Integer.toString(income);
        }
        return shortHandNumber;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAvailable;
    private javax.swing.JLabel lblAvailableForRentBackground;
    private javax.swing.JLabel lblCountOfAvailableRent;
    private javax.swing.JLabel lblCountOfRentedFlat;
    private javax.swing.JLabel lblCountOfTotalIncome;
    private javax.swing.JLabel lblFlat;
    private javax.swing.JLabel lblForRent;
    private javax.swing.JLabel lblIncome;
    private javax.swing.JLabel lblLoginClose;
    private javax.swing.JLabel lblMenuBackgroundImage;
    private javax.swing.JLabel lblMenuDashboardIcon;
    private javax.swing.JLabel lblMenuDashboardTitle;
    private javax.swing.JLabel lblMenuHomeIcon;
    private javax.swing.JLabel lblMenuHomeTitle;
    private javax.swing.JLabel lblMenuManageCleaningLog;
    private javax.swing.JLabel lblMenuManageCleaningLogIcon;
    private javax.swing.JLabel lblMenuManageFlatIcon;
    private javax.swing.JLabel lblMenuManageFlatTitle;
    private javax.swing.JLabel lblMenuManageLeftBoder;
    private javax.swing.JLabel lblMenuManageRightBoder;
    private javax.swing.JLabel lblMenuManageTenantIcon;
    private javax.swing.JLabel lblMenuManageTenantTitle;
    private javax.swing.JLabel lblMenuManageTitle;
    private javax.swing.JLabel lblMenuSettingLeftBoder;
    private javax.swing.JLabel lblMenuSettingLogoutIcon;
    private javax.swing.JLabel lblMenuSettingLogoutTitle;
    private javax.swing.JLabel lblMenuSettingRightBoder;
    private javax.swing.JLabel lblMenuSettingTitle;
    private javax.swing.JLabel lblMenuSortAndSearchFlatIcon;
    private javax.swing.JLabel lblMenuSortAndSearchFlatTitle;
    private javax.swing.JLabel lblMenuSortAndSearchLeftBoder;
    private javax.swing.JLabel lblMenuSortAndSearchRightBoder;
    private javax.swing.JLabel lblMenuSortAndSearchTenantIcon;
    private javax.swing.JLabel lblMenuSortAndSearchTenantTitle;
    private javax.swing.JLabel lblMenuSortAndSearchTitle;
    private javax.swing.JLabel lblMenuTitle;
    private javax.swing.JLabel lblMenuTitleBoder;
    private javax.swing.JLabel lblMenuTitleIcon;
    private javax.swing.JLabel lblRented;
    private javax.swing.JLabel lblRentedFlatBackground;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalIncomeBackground;
    private javax.swing.JLabel lblViewFlatDetails;
    private javax.swing.JLabel lblViewTenantDetails;
    private javax.swing.JPanel pnlDashboardMain;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlMenuDashboard;
    private javax.swing.JPanel pnlMenuHome;
    private javax.swing.JPanel pnlMenuManageCleaningLog;
    private javax.swing.JPanel pnlMenuManageFlat;
    private javax.swing.JPanel pnlMenuManageTenant;
    private javax.swing.JPanel pnlMenuSettingLogout;
    private javax.swing.JPanel pnlMenuSortAndSearchFlat;
    private javax.swing.JPanel pnlMenuSortAndSearchTenant;
    private javax.swing.JScrollPane scrlpnFlat;
    private javax.swing.JScrollPane scrlpnTenant;
    private javax.swing.JTable tblFlat;
    private javax.swing.JTable tblTenant;
    // End of variables declaration//GEN-END:variables
}
