/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.technoComplex.views;

import javax.swing.JOptionPane;

/**
 *
 * @author prajwal Luitel LMU Id 23048626
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form TechnoComplex
     */
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Calamity = new javax.swing.JLabel();
        pnlLoginMain = new javax.swing.JPanel();
        lblUsernameIcon = new javax.swing.JLabel();
        txtFldUsername = new javax.swing.JTextField();
        lblPasswordIcon = new javax.swing.JLabel();
        passFldPassword = new javax.swing.JPasswordField();
        btnLogIn = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        lblForgotPassword = new javax.swing.JLabel();
        lblLoginClose = new javax.swing.JLabel();
        lblBackgroundIcon = new javax.swing.JLabel();

        jPanel2.setMaximumSize(new java.awt.Dimension(1706, 912));
        jPanel2.setMinimumSize(new java.awt.Dimension(1706, 912));
        jPanel2.setPreferredSize(new java.awt.Dimension(1706, 912));

        Calamity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technoComplex/resources/image/background/Login.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Calamity, javax.swing.GroupLayout.PREFERRED_SIZE, 1706, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Calamity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.getAccessibleContext().setAccessibleName("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1706, 912));
        setMinimumSize(new java.awt.Dimension(1706, 912));
        setName("LogIn"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLoginMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlLoginMain.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        pnlLoginMain.setMaximumSize(new java.awt.Dimension(1706, 912));
        pnlLoginMain.setMinimumSize(new java.awt.Dimension(1706, 912));
        pnlLoginMain.setPreferredSize(new java.awt.Dimension(1706, 912));
        pnlLoginMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsernameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technoComplex/resources/image/icons/user-profile-icon-free-vector.jpg"))); // NOI18N
        pnlLoginMain.add(lblUsernameIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 69, 59));

        txtFldUsername.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        txtFldUsername.setForeground(new java.awt.Color(169, 169, 172));
        txtFldUsername.setText("Press the login button for access");
        txtFldUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 119, 182)));
        txtFldUsername.setPreferredSize(new java.awt.Dimension(25, 25));
        pnlLoginMain.add(txtFldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 230, 41));

        lblPasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technoComplex/resources/image/icons/lock_18dp_000000_FILL0_wght100_GRAD0_opsz20.png"))); // NOI18N
        pnlLoginMain.add(lblPasswordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 56, 53));

        passFldPassword.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        passFldPassword.setText("jPasswordField1");
        passFldPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 119, 182)));
        pnlLoginMain.add(passFldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 230, 42));

        btnLogIn.setBackground(new java.awt.Color(0, 119, 182));
        btnLogIn.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnLogIn.setText("Log In");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });
        pnlLoginMain.add(btnLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 123, 44));

        btnSignUp.setBackground(new java.awt.Color(0, 119, 182));
        btnSignUp.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnSignUp.setText("SIgn Up");
        pnlLoginMain.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, 123, 44));

        lblForgotPassword.setForeground(new java.awt.Color(20, 74, 134));
        lblForgotPassword.setText("Forgot password?");
        pnlLoginMain.add(lblForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 106, 20));

        lblLoginClose.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLoginClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technoComplex/resources/image/icons/close.png"))); // NOI18N
        lblLoginClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblLoginClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginCloseMouseClicked(evt);
            }
        });
        pnlLoginMain.add(lblLoginClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 0, 50, 50));

        lblBackgroundIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technoComplex/resources/image/background/Login.png"))); // NOI18N
        lblBackgroundIcon.setMaximumSize(new java.awt.Dimension(1706, 912));
        lblBackgroundIcon.setMinimumSize(new java.awt.Dimension(1706, 912));
        lblBackgroundIcon.setPreferredSize(new java.awt.Dimension(1706, 912));
        pnlLoginMain.add(lblBackgroundIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1710, 920));

        getContentPane().add(pnlLoginMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Handles the action of the login button being clicked. Closes the current
     * window and opens the home screen of the application.
     *
     * @param evt the event triggered by the login button click
     */
    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        this.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_btnLogInActionPerformed
    /**
     * Handles the mouse click event on the close label in the login window.
     * Prompts the user with a confirmation dialog to close the system. If the
     * user confirms, the application is terminated.
     *
     * @param evt the event triggered by clicking on the close label
     */
    private void lblLoginCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginCloseMouseClicked
        int closeSystem = JOptionPane.showConfirmDialog(pnlLoginMain, "Do you want to close the \nTecnho Management System", "Close System", JOptionPane.YES_NO_OPTION);
        if (closeSystem == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_lblLoginCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Calamity;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBackgroundIcon;
    private javax.swing.JLabel lblForgotPassword;
    private javax.swing.JLabel lblLoginClose;
    private javax.swing.JLabel lblPasswordIcon;
    private javax.swing.JLabel lblUsernameIcon;
    private javax.swing.JPasswordField passFldPassword;
    private javax.swing.JPanel pnlLoginMain;
    private javax.swing.JTextField txtFldUsername;
    // End of variables declaration//GEN-END:variables
}
