
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.technocomplex.views;

import com.technocomplex.controller.algorithms.MergeSort;
import com.technocomplexr.model.FlatModel;
import com.technocomplexr.model.TenantModel;
import com.technocomplex.util.TableUtil;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * <b>The SortAndSearchFlat class represents the GUI screen for sorting flat
 * data. Flat data can be sorted by FlatId, Price, Size in ascending and
 * descending order.</b>.
 *
 * <p>
 * Features include:</p>
 * <ul>
 * <li>Display sorted flat details in a tabular format</li>
 * <li>Sort by FlatId, Price, Size from JComboBox</li>
 * <li>Button to sort in ascending and descending</li>
 * <li>Navigation to various screens</li>
 * </ul>
 *
 * <p>
 * This class uses Merge Sort algorithm for sorting </p>
 *
 * @author Prajwal Luitel LMU ID 23048626
 */
public class SortAndSearchFlat extends javax.swing.JFrame {

    private List<FlatModel> flatList;
    private List<TenantModel> tenantList;
    private final MergeSort mergeSort;
    private List<FlatModel> sortedFlatList;
    private boolean isAscending;

    /**
     * Creates new form SortAndSearchFlat and populate tables with sorted flat
     * data.
     */
    public SortAndSearchFlat() {
        initComponents();
        flatList = TableUtil.initialFlatData(flatList);
        tenantList = TableUtil.initialTenantData(tenantList);
        isAscending = true;
        mergeSort = new MergeSort();
        sortedFlatList = mergeSort.sort(flatList, 0, true);
        TableUtil.designTable(tblSortedFlat);
        TableUtil.loadListDataToTable(sortedFlatList, tblSortedFlat);
    }

    /**
     * Creates new form SortAndSearchFlat populate tables with sorted flat data
     * obtained from other JFrame
     *
     * @param flatList flat data list from other JFrame
     * @param tenantList tenant data list from other JFrame
     */
    public SortAndSearchFlat(List<FlatModel> flatList, List<TenantModel> tenantList) {
        this.tenantList = new ArrayList(tenantList);
        this.flatList = new ArrayList(flatList);
        isAscending = true;
        initComponents();
        mergeSort = new MergeSort();
        sortedFlatList = mergeSort.sort(flatList, 0, true);
        TableUtil.designTable(tblSortedFlat);
        TableUtil.loadListDataToTable(sortedFlatList, tblSortedFlat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSortAndSearchFlatMain = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        lblMenuTitleIcon = new javax.swing.JLabel();
        lblMenuTitle = new javax.swing.JLabel();
        lblMenuTitleBoder = new javax.swing.JLabel();
        pnlMenuHome = new javax.swing.JPanel();
        lblMenuHomeIcon = new javax.swing.JLabel();
        lblMenuHomeTitle = new javax.swing.JLabel();
        pnlMenuDashboard = new javax.swing.JPanel();
        lblMenuDashboardIcon = new javax.swing.JLabel();
        lblMenuDashboardTitle = new javax.swing.JLabel();
        lblMenuManageLeftBoder = new javax.swing.JLabel();
        lblMenuManageTitle = new javax.swing.JLabel();
        lblMenuManageRightBoder = new javax.swing.JLabel();
        pnlMenuManageFlat = new javax.swing.JPanel();
        lblMenuManageFlatIcon = new javax.swing.JLabel();
        lblMenuManageFlatTitle = new javax.swing.JLabel();
        pnlMenuManageTenant = new javax.swing.JPanel();
        lblMenuManageTenantIcon = new javax.swing.JLabel();
        lblMenuManageTenantTitle = new javax.swing.JLabel();
        lblMenuSortAndSearchLeftBoder = new javax.swing.JLabel();
        lblMenuSortAndSearchTitle = new javax.swing.JLabel();
        lblMenuSortAndSearchRightBoder = new javax.swing.JLabel();
        pnlMenuSortAndSearchFlat = new javax.swing.JPanel();
        lblMenuSortAndSearchFlatIcon = new javax.swing.JLabel();
        lblMenuSortAndSearchFlatTitle = new javax.swing.JLabel();
        pnlMenuSortAndSearchTenant = new javax.swing.JPanel();
        lblMenuSortAndSearchTenantIcon = new javax.swing.JLabel();
        lblMenuSortAndSearchTenantTitle = new javax.swing.JLabel();
        lblMenuSettingLeftBoder = new javax.swing.JLabel();
        lblMenuSettingTitle = new javax.swing.JLabel();
        lblMenuSettingRightBoder = new javax.swing.JLabel();
        pnlMenuSettingLogout = new javax.swing.JPanel();
        lblMenuSettingLogoutIcon = new javax.swing.JLabel();
        lblMenuSettingLogoutTitle = new javax.swing.JLabel();
        pnlMenuManageCleaningLog = new javax.swing.JPanel();
        lblMenuManageCleaningLogIcon = new javax.swing.JLabel();
        lblMenuManageCleaningLog = new javax.swing.JLabel();
        lblMenuBackgroundImage = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        scrlpnSortedFlatTable = new javax.swing.JScrollPane();
        tblSortedFlat = new javax.swing.JTable();
        lblSortedFlatDetails = new javax.swing.JLabel();
        cmbxFlatFields = new javax.swing.JComboBox<>();
        btnAsecOrDesc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSortAndSearchFlatMain.setBackground(new java.awt.Color(232, 245, 255));
        pnlSortAndSearchFlatMain.setMaximumSize(new java.awt.Dimension(1706, 912));
        pnlSortAndSearchFlatMain.setMinimumSize(new java.awt.Dimension(1706, 912));
        pnlSortAndSearchFlatMain.setPreferredSize(new java.awt.Dimension(1706, 912));
        pnlSortAndSearchFlatMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenu.setMaximumSize(new java.awt.Dimension(371, 912));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuTitleIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/icons/Techno Complex White  Logo.png"))); // NOI18N
        pnlMenu.add(lblMenuTitleIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 10, 220, 150));

        lblMenuTitle.setFont(new java.awt.Font("Poppins", 2, 26)); // NOI18N
        lblMenuTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuTitle.setText("Techno Complex");
        pnlMenu.add(lblMenuTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 230, 80));

        lblMenuTitleBoder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        pnlMenu.add(lblMenuTitleBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 370, 60));

        pnlMenuHome.setMaximumSize(new java.awt.Dimension(371, 60));
        pnlMenuHome.setMinimumSize(new java.awt.Dimension(371, 60));
        pnlMenuHome.setOpaque(false);
        pnlMenuHome.setPreferredSize(new java.awt.Dimension(371, 60));
        pnlMenuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenuHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMenuHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMenuHomeMouseExited(evt);
            }
        });
        pnlMenuHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuHomeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/icons/Home.png"))); // NOI18N
        pnlMenuHome.add(lblMenuHomeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 70, 50));

        lblMenuHomeTitle.setFont(new java.awt.Font("Poppins", 0, 28)); // NOI18N
        lblMenuHomeTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuHomeTitle.setText("Home");
        pnlMenuHome.add(lblMenuHomeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        pnlMenu.add(pnlMenuHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        pnlMenuDashboard.setMaximumSize(new java.awt.Dimension(371, 60));
        pnlMenuDashboard.setMinimumSize(new java.awt.Dimension(371, 60));
        pnlMenuDashboard.setOpaque(false);
        pnlMenuDashboard.setPreferredSize(new java.awt.Dimension(371, 60));
        pnlMenuDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenuDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMenuDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMenuDashboardMouseExited(evt);
            }
        });
        pnlMenuDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuDashboardIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/icons/Dashboard.png"))); // NOI18N
        pnlMenuDashboard.add(lblMenuDashboardIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 6, -1, 48));

        lblMenuDashboardTitle.setFont(new java.awt.Font("Poppins", 0, 28)); // NOI18N
        lblMenuDashboardTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuDashboardTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuDashboardTitle.setText("Dashboard");
        pnlMenuDashboard.add(lblMenuDashboardTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 6, -1, -1));

        pnlMenu.add(pnlMenuDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        lblMenuManageLeftBoder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        pnlMenu.add(lblMenuManageLeftBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 130, 10));

        lblMenuManageTitle.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        lblMenuManageTitle.setForeground(new java.awt.Color(191, 191, 191));
        lblMenuManageTitle.setText("Manage");
        pnlMenu.add(lblMenuManageTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 90, 20));

        lblMenuManageRightBoder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        pnlMenu.add(lblMenuManageRightBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 150, 10));

        pnlMenuManageFlat.setMaximumSize(new java.awt.Dimension(371, 60));
        pnlMenuManageFlat.setMinimumSize(new java.awt.Dimension(371, 60));
        pnlMenuManageFlat.setOpaque(false);
        pnlMenuManageFlat.setPreferredSize(new java.awt.Dimension(371, 60));
        pnlMenuManageFlat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenuManageFlatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMenuManageFlatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMenuManageFlatMouseExited(evt);
            }
        });
        pnlMenuManageFlat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuManageFlatIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/icons/Manage Flat.png"))); // NOI18N
        pnlMenuManageFlat.add(lblMenuManageFlatIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 54));

        lblMenuManageFlatTitle.setFont(new java.awt.Font("Poppins", 0, 28)); // NOI18N
        lblMenuManageFlatTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuManageFlatTitle.setText("Flat");
        pnlMenuManageFlat.add(lblMenuManageFlatTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 6, -1, -1));

        pnlMenu.add(pnlMenuManageFlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        pnlMenuManageTenant.setMaximumSize(new java.awt.Dimension(371, 60));
        pnlMenuManageTenant.setMinimumSize(new java.awt.Dimension(371, 60));
        pnlMenuManageTenant.setOpaque(false);
        pnlMenuManageTenant.setPreferredSize(new java.awt.Dimension(371, 60));
        pnlMenuManageTenant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenuManageTenantMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMenuManageTenantMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMenuManageTenantMouseExited(evt);
            }
        });
        pnlMenuManageTenant.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuManageTenantIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/icons/Manage Tenant.png"))); // NOI18N
        pnlMenuManageTenant.add(lblMenuManageTenantIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 6, -1, 48));

        lblMenuManageTenantTitle.setFont(new java.awt.Font("Poppins", 0, 28)); // NOI18N
        lblMenuManageTenantTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuManageTenantTitle.setText("Tenant");
        pnlMenuManageTenant.add(lblMenuManageTenantTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 11, -1, -1));

        pnlMenu.add(pnlMenuManageTenant, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, -1, -1));

        lblMenuSortAndSearchLeftBoder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        pnlMenu.add(lblMenuSortAndSearchLeftBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 100, 10));

        lblMenuSortAndSearchTitle.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        lblMenuSortAndSearchTitle.setForeground(new java.awt.Color(191, 191, 191));
        lblMenuSortAndSearchTitle.setText("Sort and Search");
        pnlMenu.add(lblMenuSortAndSearchTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 160, 20));

        lblMenuSortAndSearchRightBoder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        pnlMenu.add(lblMenuSortAndSearchRightBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 120, 10));

        pnlMenuSortAndSearchFlat.setBackground(new java.awt.Color(97,97,97,120));
        pnlMenuSortAndSearchFlat.setMaximumSize(new java.awt.Dimension(371, 60));
        pnlMenuSortAndSearchFlat.setMinimumSize(new java.awt.Dimension(371, 60));
        pnlMenuSortAndSearchFlat.setPreferredSize(new java.awt.Dimension(371, 60));
        pnlMenuSortAndSearchFlat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuSortAndSearchFlatIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/icons/Sort and Search.png"))); // NOI18N
        pnlMenuSortAndSearchFlat.add(lblMenuSortAndSearchFlatIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 58, 51));

        lblMenuSortAndSearchFlatTitle.setFont(new java.awt.Font("Poppins", 0, 28)); // NOI18N
        lblMenuSortAndSearchFlatTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuSortAndSearchFlatTitle.setText("Flat");
        pnlMenuSortAndSearchFlat.add(lblMenuSortAndSearchFlatTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 8, -1, -1));

        pnlMenu.add(pnlMenuSortAndSearchFlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, -1, -1));

        pnlMenuSortAndSearchTenant.setMaximumSize(new java.awt.Dimension(371, 60));
        pnlMenuSortAndSearchTenant.setMinimumSize(new java.awt.Dimension(371, 60));
        pnlMenuSortAndSearchTenant.setOpaque(false);
        pnlMenuSortAndSearchTenant.setPreferredSize(new java.awt.Dimension(371, 60));
        pnlMenuSortAndSearchTenant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenuSortAndSearchTenantMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMenuSortAndSearchTenantMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMenuSortAndSearchTenantMouseExited(evt);
            }
        });
        pnlMenuSortAndSearchTenant.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuSortAndSearchTenantIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/icons/Manage Tenant.png"))); // NOI18N
        pnlMenuSortAndSearchTenant.add(lblMenuSortAndSearchTenantIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 58, 51));

        lblMenuSortAndSearchTenantTitle.setFont(new java.awt.Font("Poppins", 0, 28)); // NOI18N
        lblMenuSortAndSearchTenantTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuSortAndSearchTenantTitle.setText("Tenant");
        pnlMenuSortAndSearchTenant.add(lblMenuSortAndSearchTenantTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 8, -1, -1));

        pnlMenu.add(pnlMenuSortAndSearchTenant, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, -1, -1));

        lblMenuSettingLeftBoder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        pnlMenu.add(lblMenuSettingLeftBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 130, 10));

        lblMenuSettingTitle.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        lblMenuSettingTitle.setForeground(new java.awt.Color(191, 191, 191));
        lblMenuSettingTitle.setText("Setting");
        pnlMenu.add(lblMenuSettingTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 670, 70, 20));

        lblMenuSettingRightBoder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        pnlMenu.add(lblMenuSettingRightBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 670, 160, 10));

        pnlMenuSettingLogout.setMaximumSize(new java.awt.Dimension(371, 60));
        pnlMenuSettingLogout.setMinimumSize(new java.awt.Dimension(371, 60));
        pnlMenuSettingLogout.setOpaque(false);
        pnlMenuSettingLogout.setPreferredSize(new java.awt.Dimension(371, 60));
        pnlMenuSettingLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenuSettingLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMenuSettingLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMenuSettingLogoutMouseExited(evt);
            }
        });
        pnlMenuSettingLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuSettingLogoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/icons/Log Out.png"))); // NOI18N
        pnlMenuSettingLogout.add(lblMenuSettingLogoutIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 58, 50));

        lblMenuSettingLogoutTitle.setFont(new java.awt.Font("Poppins", 0, 28)); // NOI18N
        lblMenuSettingLogoutTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuSettingLogoutTitle.setText("Log Out");
        pnlMenuSettingLogout.add(lblMenuSettingLogoutTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 8, -1, -1));

        pnlMenu.add(pnlMenuSettingLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, -1, -1));

        pnlMenuManageCleaningLog.setMinimumSize(new java.awt.Dimension(371, 60));
        pnlMenuManageCleaningLog.setOpaque(false);
        pnlMenuManageCleaningLog.setPreferredSize(new java.awt.Dimension(371, 60));
        pnlMenuManageCleaningLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenuManageCleaningLogMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMenuManageCleaningLogMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMenuManageCleaningLogMouseExited(evt);
            }
        });
        pnlMenuManageCleaningLog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuManageCleaningLogIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/icons/Cleaning Log.png"))); // NOI18N
        pnlMenuManageCleaningLog.add(lblMenuManageCleaningLogIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 60));

        lblMenuManageCleaningLog.setFont(new java.awt.Font("Poppins", 0, 28)); // NOI18N
        lblMenuManageCleaningLog.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuManageCleaningLog.setText("Cleaning Log");
        pnlMenuManageCleaningLog.add(lblMenuManageCleaningLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 11, -1, -1));

        pnlMenu.add(pnlMenuManageCleaningLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, -1, -1));

        lblMenuBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/background/Menu.png"))); // NOI18N
        pnlMenu.add(lblMenuBackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlSortAndSearchFlatMain.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/icons/Close.png"))); // NOI18N
        lblClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        pnlSortAndSearchFlatMain.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 0, 50, 50));

        scrlpnSortedFlatTable.setBackground(new java.awt.Color(0, 255, 204));
        scrlpnSortedFlatTable.setForeground(new java.awt.Color(255, 255, 255));
        scrlpnSortedFlatTable.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblSortedFlat.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tblSortedFlat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FlatId", "Price", "Size", "Livingroom", "Bedroom", "Kitchen", "Furnish", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Byte.class, java.lang.Byte.class, java.lang.Byte.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSortedFlat.setRowHeight(30);
        tblSortedFlat.getTableHeader().setReorderingAllowed(false);
        scrlpnSortedFlatTable.setViewportView(tblSortedFlat);
        if (tblSortedFlat.getColumnModel().getColumnCount() > 0) {
            tblSortedFlat.getColumnModel().getColumn(0).setResizable(false);
            tblSortedFlat.getColumnModel().getColumn(1).setResizable(false);
            tblSortedFlat.getColumnModel().getColumn(2).setResizable(false);
            tblSortedFlat.getColumnModel().getColumn(3).setResizable(false);
            tblSortedFlat.getColumnModel().getColumn(4).setResizable(false);
            tblSortedFlat.getColumnModel().getColumn(5).setResizable(false);
            tblSortedFlat.getColumnModel().getColumn(6).setResizable(false);
            tblSortedFlat.getColumnModel().getColumn(7).setResizable(false);
        }

        pnlSortAndSearchFlatMain.add(scrlpnSortedFlatTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 1210, 460));

        lblSortedFlatDetails.setFont(new java.awt.Font("Poppins", 0, 38)); // NOI18N
        lblSortedFlatDetails.setForeground(new java.awt.Color(102, 153, 255));
        lblSortedFlatDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSortedFlatDetails.setText("Sorted Flat Details");
        pnlSortAndSearchFlatMain.add(lblSortedFlatDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 1210, 60));

        cmbxFlatFields.setBackground(new java.awt.Color(102, 153, 255));
        cmbxFlatFields.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        cmbxFlatFields.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FlatId", "Price", "Size" }));
        cmbxFlatFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxFlatFieldsActionPerformed(evt);
            }
        });
        pnlSortAndSearchFlatMain.add(cmbxFlatFields, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 50, 150, 50));

        btnAsecOrDesc.setBackground(new java.awt.Color(102, 153, 255));
        btnAsecOrDesc.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnAsecOrDesc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/icons/Ascending.png"))); // NOI18N
        btnAsecOrDesc.setText("Ascending");
        btnAsecOrDesc.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAsecOrDesc.setPreferredSize(new java.awt.Dimension(150, 50));
        btnAsecOrDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsecOrDescActionPerformed(evt);
            }
        });
        pnlSortAndSearchFlatMain.add(btnAsecOrDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 50, 150, -1));

        getContentPane().add(pnlSortAndSearchFlatMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Turn the background light and show underline for label when mouse entered
     * the menu item i.e hover effect.
     *
     * @param menuPanel the menu item panel in which light background (hover
     * effect) is to be shown
     * @param menuPanelLabel the menu title label in which underline label
     * (hover effect) is to be shown
     */
    private void mouseEnter(JPanel menuPanel, JLabel menuPanelLabel) {
        menuPanel.setBackground(null);
        menuPanel.setBackground(new Color(192, 213, 255));
        menuPanel.setOpaque(true);
        menuPanelLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
    }

    /**
     * Remove the hover effect when mouse leave the menu item.
     *
     * @param menuPanel the menu item panel to turn it back to normal
     * @param menuPanelLabel the menu title label to turn it back to normal
     *
     */
    private void mouseExit(JPanel menuPanel, JLabel menuPanelLabel) {
        menuPanel.setBackground(null);
        menuPanel.setOpaque(false);
        menuPanelLabel.setBorder(null);
    }

    /**
     * Handles the mouse click event on the Menu Home panel. Direct the user to
     * Home screen and dispose this screen.
     *
     * @param evt the event triggered by clicking on the Menu Home panel
     */
    private void pnlMenuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuHomeMouseClicked
        new Home(flatList, tenantList).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlMenuHomeMouseClicked

    /**
     * Handles the mouse Enter event on the Menu Home panel. Hover effect on
     * Menu Home panel is created.
     *
     * @param evt the event triggered by entering on the Menu Home panel.
     */
    private void pnlMenuHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuHomeMouseEntered
        mouseEnter(pnlMenuHome, lblMenuHomeTitle);
    }//GEN-LAST:event_pnlMenuHomeMouseEntered

    /**
     * Handles the mouse Exit event on the Menu Home panel. Menu Home panel is
     * turned back to normal by removing hover effect.
     *
     * @param evt the event triggered by exiting on the Menu Home panel.
     */
    private void pnlMenuHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuHomeMouseExited
        mouseExit(pnlMenuHome, lblMenuHomeTitle);
    }//GEN-LAST:event_pnlMenuHomeMouseExited

    /**
     * Handles the mouse click event on the Menu Dashboard panel. Direct the
     * user to Dashboard screen and dispose this screen.
     *
     * @param evt the event triggered by clicking on the Menu Dashboard panel
     */
    private void pnlMenuDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuDashboardMouseClicked
        new Dashboard(flatList, tenantList).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlMenuDashboardMouseClicked

    /**
     * Handles the mouse Enter event on the Menu Dashboard panel. Hover effect
     * on Menu Dashboard panel is created.
     *
     * @param evt the event triggered by entering on the Menu Dashboard panel.
     */
    private void pnlMenuDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuDashboardMouseEntered
        mouseEnter(pnlMenuDashboard, lblMenuDashboardTitle);
    }//GEN-LAST:event_pnlMenuDashboardMouseEntered

    /**
     * Handles the mouse Exit event on the Menu Dashboard panel. Menu Dashboard
     * panel is turned back to normal by removing hover effect.
     *
     * @param evt the event triggered by exiting on the Menu Dashboard panel.
     */
    private void pnlMenuDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuDashboardMouseExited
        mouseExit(pnlMenuDashboard, lblMenuDashboardTitle);
    }//GEN-LAST:event_pnlMenuDashboardMouseExited

    /**
     * Handles the mouse click event on the Menu Manage Flat panel. Direct the
     * user to Manage Flat screen and dispose this screen.
     *
     * @param evt the event triggered by clicking on the Menu Manage Flat panel
     */
    private void pnlMenuManageFlatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuManageFlatMouseClicked
        new ManageFlat(flatList, tenantList).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlMenuManageFlatMouseClicked

    /**
     * Handles the mouse Enter event on the Menu Manage Flat panel. Hover effect
     * on Menu Manage Flat panel is created.
     *
     * @param evt the event triggered by entering on the Menu Manage Flat panel.
     */
    private void pnlMenuManageFlatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuManageFlatMouseEntered
        mouseEnter(pnlMenuManageFlat, lblMenuManageFlatTitle);
    }//GEN-LAST:event_pnlMenuManageFlatMouseEntered

    /**
     * Handles the mouse Exit event on the Menu Manage Flat panel. Menu Manage
     * Flat panel is turned back to normal by removing hover effect.
     *
     * @param evt the event triggered by exiting on the Menu Manage Flat panel.
     */
    private void pnlMenuManageFlatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuManageFlatMouseExited
        mouseExit(pnlMenuManageFlat, lblMenuManageFlatTitle);
    }//GEN-LAST:event_pnlMenuManageFlatMouseExited

    /**
     * Handles the mouse click event on the Menu Manage Tenant panel. Direct the
     * user to Manage Tenant screen and dispose this screen.
     *
     * @param evt the event triggered by clicking on the Menu Manage Tenant
     * panel
     */
    private void pnlMenuManageTenantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuManageTenantMouseClicked
        new ManageTenant(flatList, tenantList).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlMenuManageTenantMouseClicked

    /**
     * Handles the mouse Enter event on the Menu Manage Tenant panel. Hover
     * effect on Menu Manage Tenant panel is created.
     *
     * @param evt the event triggered by entering on the Menu Manage Tenant
     * panel.
     */
    private void pnlMenuManageTenantMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuManageTenantMouseEntered
        mouseEnter(pnlMenuManageTenant, lblMenuManageTenantTitle);
    }//GEN-LAST:event_pnlMenuManageTenantMouseEntered

    /**
     * Handles the mouse Exit event on the Menu Manage Tenant panel. Menu Manage
     * Tenant panel is turned back to normal by removing hover effect.
     *
     * @param evt the event triggered by exiting on the Menu Manage Tenant
     * panel.
     */
    private void pnlMenuManageTenantMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuManageTenantMouseExited
        mouseExit(pnlMenuManageTenant, lblMenuManageTenantTitle);
    }//GEN-LAST:event_pnlMenuManageTenantMouseExited

    /**
     * Handles the mouse click event on the Menu Cleaning Log panel. Direct the
     * user to Cleaning Log screen and dispose this screen.
     *
     * @param evt the event triggered by clicking on the Menu Cleaning Log panel
     */
    private void pnlMenuManageCleaningLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuManageCleaningLogMouseClicked
        new CleaningLog(flatList, tenantList).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlMenuManageCleaningLogMouseClicked

    /**
     * Handles the mouse Enter event on the Menu Cleaning Log panel. Hover
     * effect on Menu Cleaning Log panel is created.
     *
     * @param evt the event triggered by entering on the Menu Cleaning Log
     * panel.
     */
    private void pnlMenuManageCleaningLogMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuManageCleaningLogMouseEntered
        mouseEnter(pnlMenuManageCleaningLog, lblMenuManageCleaningLog);
    }//GEN-LAST:event_pnlMenuManageCleaningLogMouseEntered

    /**
     * Handles the mouse Exit event on the Menu Cleaning Log panel. Menu
     * Cleaning Log panel is turned back to normal by removing hover effect.
     *
     * @param evt the event triggered by exiting on the Menu Cleaning Log panel.
     */
    private void pnlMenuManageCleaningLogMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuManageCleaningLogMouseExited
        mouseExit(pnlMenuManageCleaningLog, lblMenuManageCleaningLog);
    }//GEN-LAST:event_pnlMenuManageCleaningLogMouseExited

    /**
     * Handles the mouse click event on the Menu Sort and Search Tenant panel.
     * Direct the user to Sort and Search Tenant screen and dispose this screen.
     *
     * @param evt the event triggered by clicking on the Menu Sort and Search
     * Tenant panel
     */
    private void pnlMenuSortAndSearchTenantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuSortAndSearchTenantMouseClicked
        new SortAndSearchTenant(flatList, tenantList).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlMenuSortAndSearchTenantMouseClicked

    /**
     * Handles the mouse Enter event on the Menu Sort and Search Tenant panel.
     * Hover effect on Menu Sort and Search Tenant panel is created.
     *
     * @param evt the event triggered by entering on the Menu Sort and Search
     * Tenant panel.
     */
    private void pnlMenuSortAndSearchTenantMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuSortAndSearchTenantMouseEntered
        mouseEnter(pnlMenuSortAndSearchTenant, lblMenuSortAndSearchTenantTitle);
    }//GEN-LAST:event_pnlMenuSortAndSearchTenantMouseEntered

    /**
     * Handles the mouse Exit event on the Menu Sort and Search Tenant panel.
     * Menu Sort and Search Tenant panel is turned back to normal by removing
     * hover effect.
     *
     * @param evt the event triggered by exiting on the Menu Sort and Search
     * Tenant panel.
     */
    private void pnlMenuSortAndSearchTenantMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuSortAndSearchTenantMouseExited
        mouseExit(pnlMenuSortAndSearchTenant, lblMenuSortAndSearchTenantTitle);
    }//GEN-LAST:event_pnlMenuSortAndSearchTenantMouseExited

    /**
     * Handles the mouse click event on the Menu Log Out panel. Direct the user
     * to Log In screen and dispose this screen.
     *
     * @param evt the event triggered by clicking on the Menu Log Out panel
     */
    private void pnlMenuSettingLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuSettingLogoutMouseClicked
        new LogIn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlMenuSettingLogoutMouseClicked

    /**
     * Handles the mouse Enter event on the Menu Log Out panel. Hover effect on
     * Menu Log Out panel is created.
     *
     * @param evt the event triggered by entering on the Menu Log Out panel.
     */
    private void pnlMenuSettingLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuSettingLogoutMouseEntered
        mouseEnter(pnlMenuSettingLogout, lblMenuSettingLogoutTitle);
    }//GEN-LAST:event_pnlMenuSettingLogoutMouseEntered

    /**
     * Handles the mouse Exit event on the Menu Log Out panel. Menu Log Out
     * panel is turned back to normal by removing hover effect.
     *
     * @param evt the event triggered by exiting on the Menu Log Out panel.
     */
    private void pnlMenuSettingLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuSettingLogoutMouseExited
        mouseExit(pnlMenuSettingLogout, lblMenuSettingLogoutTitle);
    }//GEN-LAST:event_pnlMenuSettingLogoutMouseExited

    /**
     * Handles the mouse click event on the close label in the Sort and Search
     * Flat window. Prompts the user with a confirmation dialog to close the
     * system. If the user confirms, the application is terminated.
     *
     * @param evt the event triggered by clicking on the close label
     */
    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        int closeSystem = JOptionPane.showConfirmDialog(pnlSortAndSearchFlatMain, "Do you want to close the \nTecnho Management System", "Close System", JOptionPane.YES_NO_OPTION);
        if (closeSystem == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_lblCloseMouseClicked

    /**
     * Event handler for the FlatFields COmboBox action. sort the list according
     * to the field in the ComboBox.
     *
     * @param evt the ActionEvent triggered by the FlatFields COmboBox
     */
    private void cmbxFlatFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxFlatFieldsActionPerformed
        //Checking for empty list
        if (flatList.isEmpty()) {
            JOptionPane.showConfirmDialog(pnlSortAndSearchFlatMain, "Cannot sort from empty data.\nSort after filling the data", "Empty Data.", JOptionPane.ERROR_MESSAGE);
            return;
        }
        sortedFlatList = mergeSort.sort(flatList, cmbxFlatFields.getSelectedIndex(), isAscending);
        TableUtil.loadListDataToTable(sortedFlatList, tblSortedFlat);
    }//GEN-LAST:event_cmbxFlatFieldsActionPerformed

    /**
     * Event handler for the AsecOrDesc button action. sort the list according
     * to the icon in the button and the icon is changed after sort.
     *
     * @param evt the ActionEvent triggered by the AsecOrDesc button
     */
    private void btnAsecOrDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsecOrDescActionPerformed
        //when button icon is ascending
        if (isAscending) {
            btnAsecOrDesc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/icons/Descending.png"))); // NOI18N
            btnAsecOrDesc.setText("Descending");
            isAscending = false;
            //Checking for empty list
            if (flatList.isEmpty()) {
                JOptionPane.showConfirmDialog(pnlSortAndSearchFlatMain, "Cannot sort from empty data.\nSort after filling the data", "Empty Data.", JOptionPane.ERROR_MESSAGE);
                return;
            }
            sortedFlatList = mergeSort.sort(flatList, cmbxFlatFields.getSelectedIndex(), isAscending);
            TableUtil.loadListDataToTable(sortedFlatList, tblSortedFlat);
        } else {
            // button icon is descending
            btnAsecOrDesc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/technocomplex/resources/images/icons/Ascending.png"))); // NOI18N
            btnAsecOrDesc.setText("Ascending");
            isAscending = true;
            //Checking for empty list
            if (flatList.isEmpty()) {
                JOptionPane.showConfirmDialog(pnlSortAndSearchFlatMain, "Cannot sort from empty data.\nSort after filling the data", "Empty Data.", JOptionPane.ERROR_MESSAGE);
                return;
            }
            sortedFlatList = mergeSort.sort(flatList, cmbxFlatFields.getSelectedIndex(), isAscending);
            TableUtil.loadListDataToTable(sortedFlatList, tblSortedFlat);
        }
    }//GEN-LAST:event_btnAsecOrDescActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SortAndSearchFlat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SortAndSearchFlat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SortAndSearchFlat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SortAndSearchFlat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SortAndSearchFlat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsecOrDesc;
    private javax.swing.JComboBox<String> cmbxFlatFields;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblMenuBackgroundImage;
    private javax.swing.JLabel lblMenuDashboardIcon;
    private javax.swing.JLabel lblMenuDashboardTitle;
    private javax.swing.JLabel lblMenuHomeIcon;
    private javax.swing.JLabel lblMenuHomeTitle;
    private javax.swing.JLabel lblMenuManageCleaningLog;
    private javax.swing.JLabel lblMenuManageCleaningLogIcon;
    private javax.swing.JLabel lblMenuManageFlatIcon;
    private javax.swing.JLabel lblMenuManageFlatTitle;
    private javax.swing.JLabel lblMenuManageLeftBoder;
    private javax.swing.JLabel lblMenuManageRightBoder;
    private javax.swing.JLabel lblMenuManageTenantIcon;
    private javax.swing.JLabel lblMenuManageTenantTitle;
    private javax.swing.JLabel lblMenuManageTitle;
    private javax.swing.JLabel lblMenuSettingLeftBoder;
    private javax.swing.JLabel lblMenuSettingLogoutIcon;
    private javax.swing.JLabel lblMenuSettingLogoutTitle;
    private javax.swing.JLabel lblMenuSettingRightBoder;
    private javax.swing.JLabel lblMenuSettingTitle;
    private javax.swing.JLabel lblMenuSortAndSearchFlatIcon;
    private javax.swing.JLabel lblMenuSortAndSearchFlatTitle;
    private javax.swing.JLabel lblMenuSortAndSearchLeftBoder;
    private javax.swing.JLabel lblMenuSortAndSearchRightBoder;
    private javax.swing.JLabel lblMenuSortAndSearchTenantIcon;
    private javax.swing.JLabel lblMenuSortAndSearchTenantTitle;
    private javax.swing.JLabel lblMenuSortAndSearchTitle;
    private javax.swing.JLabel lblMenuTitle;
    private javax.swing.JLabel lblMenuTitleBoder;
    private javax.swing.JLabel lblMenuTitleIcon;
    private javax.swing.JLabel lblSortedFlatDetails;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlMenuDashboard;
    private javax.swing.JPanel pnlMenuHome;
    private javax.swing.JPanel pnlMenuManageCleaningLog;
    private javax.swing.JPanel pnlMenuManageFlat;
    private javax.swing.JPanel pnlMenuManageTenant;
    private javax.swing.JPanel pnlMenuSettingLogout;
    private javax.swing.JPanel pnlMenuSortAndSearchFlat;
    private javax.swing.JPanel pnlMenuSortAndSearchTenant;
    private javax.swing.JPanel pnlSortAndSearchFlatMain;
    private javax.swing.JScrollPane scrlpnSortedFlatTable;
    private javax.swing.JTable tblSortedFlat;
    // End of variables declaration//GEN-END:variables
}
